Huila

diff --git a/pipeline/build/jobs/job-iac.yml b/pipeline/build/jobs/job-iac.yml
--- a/pipeline/build/jobs/job-iac.yml
+++ b/pipeline/build/jobs/job-iac.yml
@@ -97,44 +97,154 @@ jobs:
             set -e
 
             
-            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-apigateway-metabase
+            # # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-apigateway-metabase
+            # # terragrunt plan --all --non-interactive --no-color
+            # # terragrunt apply --all --non-interactive --no-color
+
+            # # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-apigateway-domain-names-metabase
+            # # terragrunt plan --all --non-interactive --no-color
+            # # terragrunt apply --all --non-interactive --no-color
+
+            # # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-iam-profile/ecs-task-execution-role
+            # # terragrunt plan --all --non-interactive --no-color
+            # # terragrunt apply --all --non-interactive --no-color
+
+            # # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/metabase/aws-service-ecs
+            # # terragrunt plan --all --non-interactive --no-color
+            # # terragrunt apply --all --non-interactive --no-color
+
+            # # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-secret-manager-aes
+            # # terragrunt plan --all --non-interactive --no-color
+            # # terragrunt apply --all --non-interactive --no-color
+
+            # # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-ssm-parameter
+            # # terragrunt plan --all --non-interactive --no-color
+            # # terragrunt apply --all --non-interactive --no-color
+
+            # # echo "*********************redis***********************"
+
+            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/transaction-notifier
             # terragrunt plan --all --non-interactive --no-color
             # terragrunt apply --all --non-interactive --no-color
 
-            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-apigateway-domain-names-metabase
+            # echo "*********************remittances***********************"
+
+            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/wiretransfer
             # terragrunt plan --all --non-interactive --no-color
             # terragrunt apply --all --non-interactive --no-color
-
-            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-iam-profile/ecs-task-execution-role
-            # terragrunt plan --all --non-interactive --no-color
-            # terragrunt apply --all --non-interactive --no-color
-
-            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/metabase/aws-service-ecs
-            # terragrunt plan --all --non-interactive --no-color
-            # terragrunt apply --all --non-interactive --no-color
-
-            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-secret-manager-aes
-            # terragrunt plan --all --non-interactive --no-color
-            # terragrunt apply --all --non-interactive --no-color
-
-            # cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/initial-infrastructure/aws-service-ssm-parameter
-            # terragrunt plan --all --non-interactive --no-color
-            # terragrunt apply --all --non-interactive --no-color
-
-            # echo "*********************redis***********************"
-
-            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/transaction-notifier
-            terragrunt plan --all --non-interactive --no-color
-            terragrunt apply --all --non-interactive --no-color
-
-            echo "*********************remittances***********************"
-
-            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima/wiretransfer
-            terragrunt plan --all --non-interactive --no-color
-            terragrunt apply --all --non-interactive --no-color
 
           displayName: "✔️ Plan"
           workingDirectory: $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/tolima
+          env:
+            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
+            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
+            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+  - ${{ if eq(variables['Build.SourceBranchName'], 'huila') }}:
+    - job: "build_iac_sebas_huila"
+      displayName: "Build Infrastructure"
+      pool:
+        name: "Azure Pipelines"
+        vmImage: "ubuntu-22.04"
+
+      variables:
+        versionTerraform: $[coalesce(variables.terraformVersion, '1.12.0')]
+        versionTerragrunt: $[coalesce(variables.terragruntVersion, '0.84.1')]
+
+      steps:
+        - script: |
+            echo -e "\n📋 Variables disponibles:"
+            printenv | sort | grep -i "aws_" || true
+
+            echo -e "\n📋 Parametros disponibles:"
+            printenv | sort | grep -i "parameter_" || true
+          displayName: "📋 Environment variables"
+
+        - script: |
+            echo "📥 Descargando Terragrunt..."
+            aws s3 cp "s3://infrastructure-as-code-invictus/terragrunt/terragrunt-$(versionTerragrunt)" "terragrunt"
+
+            if [ ! -s terragrunt ]; then
+              echo "❌ Error: No se pudo descargar terragrunt: $(versionTerragrunt)"
+              exit 99
+            fi
+
+            chmod +x terragrunt
+            sudo mv terragrunt /usr/local/bin/terragrunt
+
+            echo -e "\n🚀 Terragrunt instalado correctamente:"
+            terragrunt --version
+          displayName: "🛠️ Instalar Terragrunt"
+          env:
+            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+        - script: |
+            echo "📥 Descargando Terraform..."
+            aws s3 cp "s3://infrastructure-as-code-invictus/terraform/terraform-$(versionTerraform)" "terraform"
+
+            if [ ! -s terraform ]; then
+              echo "❌ Error: No se pudo descargar terraform: $(versionTerraform)"
+              exit 99
+            fi
+
+            chmod +x terraform
+            sudo mv terraform /usr/local/bin/terraform
+
+            echo -e "\n🚀 Terraform instalado correctamente:"
+            terraform --version
+          displayName: "🛠️ Instalar terraform"
+          env:
+            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+        - task: replacetokens@5
+          inputs:
+            targetFiles: |
+              $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/**/terragrunt.hcl
+              $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/root.hcl
+              $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/backend.tf
+              $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/provider.tf
+            encoding: "auto"
+            writeBOM: true
+            actionOnMissing: "warn" # 'fail', 'warn' o 'ignore'
+            keepToken: false
+            tokenPrefix: "#{"
+            tokenSuffix: "}#"
+          displayName: "⚙️ Replace Tokens"
+
+        - script: |
+            set -e
+
+            
+            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/initial-infrastructure/aws-service-apigateway-metabase
+            terragrunt plan --all --non-interactive --no-color
+            # terragrunt apply --all --non-interactive --no-color
+
+            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/initial-infrastructure/aws-service-apigateway-domain-names-metabase
+            terragrunt plan --all --non-interactive --no-color
+            # terragrunt apply --all --non-interactive --no-color
+
+            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/initial-infrastructure/aws-service-iam-profile/ecs-task-execution-role
+            terragrunt plan --all --non-interactive --no-color
+            # terragrunt apply --all --non-interactive --no-color
+
+            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/metabase/aws-service-ecs
+            terragrunt plan --all --non-interactive --no-color
+            # terragrunt apply --all --non-interactive --no-color
+
+            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/initial-infrastructure/aws-service-kinesis-ckm
+            terragrunt plan --all --non-interactive --no-color
+            # terragrunt apply --all --non-interactive --no-color
+
+            cd $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila/initial-infrastructure/aws-service-ssm-parameter
+            terragrunt plan --all --non-interactive --no-color
+            # terragrunt apply --all --non-interactive --no-color
+
+          displayName: "✔️ Plan"
+          workingDirectory: $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/huila
           env:
             AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
             AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
