Updates electron

diff --git a/pipeline/build/jobs/job-electron.yml b/pipeline/build/jobs/job-electron.yml
--- a/pipeline/build/jobs/job-electron.yml
+++ b/pipeline/build/jobs/job-electron.yml
@@ -18,13 +18,13 @@ jobs:
 
   - job: "build_electron_windows"
     ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
-      displayName: "Build Electron Feature"
+      displayName: "Build Electron Windows Feature"
     ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
-      displayName: "Build Electron Develop"
+      displayName: "Build Electron Windows Develop"
     ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
-      displayName: "Build Electron Staging"
+      displayName: "Build Electron Windows Staging"
     ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
-      displayName: "Build Electron Master ${{ parameters.red }}"
+      displayName: "Build Electron Windows Master ${{ parameters.red }}"
     pool:
       vmImage: "windows-latest"
     variables:
@@ -275,6 +275,92 @@ jobs:
 
             aws s3 cp "$basePath" "s3://e-remote/invictus-electron/windows/$($env:region)" --recursive --acl public-read
         condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
+        env:
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+  - job: "build_electron_linux"
+    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
+      displayName: "Build Electron Linux Feature"
+    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
+      displayName: "Build Electron Linux Develop"
+    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
+      displayName: "Build Electron Linux Staging"
+    ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
+      displayName: "Build Electron Linux Master ${{ parameters.red }}"
+    pool:
+      vmImage: "ubuntu-22.04"
+    variables:
+      versionNode: $[coalesce(variables.nodeVersion, '18.20.7')]
+      versionPython: $[coalesce(variables.pythonVersion, '3.24.0')]
+
+
+    steps:
+
+      - task: DownloadBuildArtifacts@0
+        displayName: "📥 Download Version Artifact"
+        inputs:
+          artifactName: "versions"
+          downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
+      
+      - script: |
+          ls -R $(Pipeline.Workspace)/downloaded-versions/versions
+          VERSION_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/version.json"
+          if [[ -f "$VERSION_FILE" ]]; then
+            VERSION=$(jq -r '.version' $VERSION_FILE)            
+            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
+            echo "##vso[task.setvariable variable=msVersion]$VERSION"
+          else
+            echo "##vso[task.logissue type=error]❌ No se encontro archivo de versión para $(Build.Repository.Name)"
+            exit 99
+          fi
+        displayName: "📖 Read Microservice Versions"
+
+      - task: UsePythonVersion@0
+        displayName: "🔧 Use Python $(versionPython)"
+        inputs:
+          versionSpec: "$(versionPython)"
+          addToPath: true
+
+      - task: NodeTool@0
+        displayName: "🔧 Install Nodejs $(versionNode)"
+        inputs:
+          versionSource: "spec"
+          versionSpec: "$(versionNode)"
+
+      - task: Bash@3
+        name: AuthCodeArtifact
+        inputs:
+          targetType: "inline"
+          script: |
+            echo "🔐 Obteniendo token de AWS CodeArtifact..."
+            token=$(aws codeartifact get-authorization-token \
+              --domain matrixtech-npm-repository \
+              --domain-owner "$ACCOUNT_ID_DEPLOY" \
+              --region "$AWS_DEFAULT_REGION" \
+              --query authorizationToken \
+              --output text)
+
+            REPO_DOMAIN="matrixtech-npm-repository-$ACCOUNT_ID_DEPLOY.d.codeartifact.$AWS_DEFAULT_REGION.amazonaws.com"
+            REPO_PATH="npm/matrixtech-npm-repository"
+            REPO_URL="https://$REPO_DOMAIN/$REPO_PATH"
+
+            echo "Configurando npm..."
+            npm config set "//$REPO_DOMAIN/$REPO_PATH/:_authToken" "$token"
+            npm config set registry "$REPO_URL"
+
+            echo "Verificando identidad de AWS..."
+            aws sts get-caller-identity
+
+
+            echo "Generando archivo .npmrc"
+            cat <<EOF > ".npmrc"
+            //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
+            registry=$REPO_URL
+            EOF
+            ls -la .npmrc
+        displayName: "🔐 Setup CodeArtifact & npm config"
         env:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
