Deploy apigateway

diff --git a/pipeline/build/jobs/job-electron.yml b/pipeline/build/jobs/job-electron.yml
--- a/pipeline/build/jobs/job-electron.yml
+++ b/pipeline/build/jobs/job-electron.yml
@@ -1,4 +1,6 @@
 jobs:
+
+  # Electron Windows
   - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')) }}:
       - deployment: WaitForApproval
         displayName: "Esperar aprobación"
@@ -40,7 +42,7 @@ jobs:
           downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
 
       - task: PowerShell@2
-        displayName: "📚 Read exe versions"
+        displayName: "📚 Read version"
         inputs:
           targetType: "inline"
           script: |
@@ -280,6 +282,8 @@ jobs:
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
 
+
+  # Electron Linux
   - job: "build_electron_linux"
     ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
       displayName: "Build Electron Linux Feature"
@@ -305,7 +309,8 @@ jobs:
         displayName: "📥 Download Version Artifact"
 
       - script: |
-          ls -R $(Pipeline.Workspace)/downloaded-versions/versions
+          echo -e "\n📁 Archivo version.json:"
+          ls -la $(Pipeline.Workspace)/downloaded-versions/versions/electron/
           VERSION_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/electron/version.json"
           if [[ -f "$VERSION_FILE" ]]; then
             VERSION=$(jq -r '.version' $VERSION_FILE)
@@ -313,22 +318,10 @@ jobs:
             echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION_CLEAN"
             echo "##vso[task.setvariable variable=msVersion]$VERSION_CLEAN"
           else
-            echo "##vso[task.logissue type=error]❌ No se encontro archivo de versión para $(Build.Repository.Name)"
+            echo -e "\n##vso[task.logissue type=error]❌ No se encontro archivo de versión para $(Build.Repository.Name)"
             exit 99
           fi
-        displayName: "📖 Read Microservice Versions"
-
-      - task: UsePythonVersion@0
-        displayName: "🔧 Use Python $(versionPython)"
-        inputs:
-          versionSpec: "$(versionPython)"
-          addToPath: true
-
-      - task: NodeTool@0
-        displayName: "🔧 Install Nodejs $(versionNode)"
-        inputs:
-          versionSource: "spec"
-          versionSpec: "$(versionNode)"
+        displayName: "📚 Read version"
 
       - task: Bash@3
         name: AuthCodeArtifact
@@ -354,7 +347,6 @@ jobs:
             echo "Verificando identidad de AWS..."
             aws sts get-caller-identity
 
-
             echo "Generando archivo .npmrc"
             cat <<EOF > ".npmrc"
             //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
@@ -366,3 +358,57 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      - script: |
+          CURRENT_BRANCH="$(Build.SourceBranch)"
+          environment="unknown"
+          region="unknown"
+
+          case "$CURRENT_BRANCH" in
+            refs/heads/feature/*) environment="dev"; region="dev"; ;;
+            refs/heads/develop)   environment="dev"; region="dev"; ;;
+            refs/heads/staging)   environment="qa";  region="qa"; ;;
+            refs/heads/master) 
+              case "$red" in
+                "antioquia") environment="production"; region="matrixtech"; ;;
+                "cap")       environment="production"; region="cap"; ;;
+                "tolima")    environment="production"; region="seapto"; ;;
+                "huila")     environment="production"; region="suchance"; ;;
+                "cauca")     environment="production"; region="acertemos"; ;;
+                "boyaca")    environment="production"; region="jer"; ;;
+              esac ;;
+          esac
+
+          if [ "$environment" = "unknown" ] || [ "$region" = "unknown" ]; then
+            echo "⚠️ Environment [$environment] no reconocido"
+            echo "⚠️ Región [$region] no reconocida"
+            exit 99
+          fi
+
+          cat <<EOF > .env
+          DOMAIN_ADMIN="${BASE_URL_ELECTRON_ADMIN}"
+          DOMAIN_SELLER="${BASE_URL_ELECTRON_SELLERS}"
+          TARGET="linux"
+          TARGET_ENVIRONMENT="$environment"
+          EOF
+
+          echo "##vso[task.setvariable variable=environment]$environment"
+          echo "##vso[task.setvariable variable=region]$region"
+
+          echo -e "\n✅ Archivo .env creado correctamente"
+          cat .env
+        displayName: "⚙️ Generate .env"
+        env:
+          red: ${{ parameters.red }}
+
+      - task: UsePythonVersion@0
+        displayName: "🔧 Use Python $(versionPython)"
+        inputs:
+          versionSpec: "$(versionPython)"
+          addToPath: true
+
+      - task: NodeTool@0
+        displayName: "🔧 Install Nodejs $(versionNode)"
+        inputs:
+          versionSource: "spec"
+          versionSpec: "$(versionNode)"
