Update job iac

diff --git a/pipeline/build/jobs/job-iac.yml b/pipeline/build/jobs/job-iac.yml
--- a/pipeline/build/jobs/job-iac.yml
+++ b/pipeline/build/jobs/job-iac.yml
@@ -30,18 +30,75 @@ jobs:
 
     steps:
 
-      - task: TerraformInstaller@1
-        inputs:
-          terraformVersion: $(TerraformVersion)
-
       - script: |
-          sudo apt-get update -y
-          sudo apt-get install -y unzip
-          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.84.1/terragrunt_linux_amd64
-          chmod +x terragrunt_linux_amd64
-          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
+          echo "📥 Descargando Terragrunt..."
+          aws s3 cp "s3://infrastructure-as-code-invictus/terragrunt/terragrunt-$(terragruntVersion)" "terragrunt"
+
+          # Validar que el archivo se descargó
+          if [ ! -s terragrunt ]; then
+            echo "❌ Error: No se pudo descargar terragrunt: $(terragruntVersion)"
+            exit 99
+          fi
+
+          # Hacerlo ejecutable y moverlo
+          chmod +x terragrunt
+          sudo mv terragrunt /usr/local/bin/terragrunt
+
+          echo -e "\n🚀 Terragrunt instalado correctamente:"
           terragrunt --version
         displayName: "Instalar Terragrunt"
+        env:
+          AWS_ACCESS_KEY_ID: $(ACCOUNT_ID_DEPLOY)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      - script: |
+          echo "📥 Descargando Terraform..."
+          aws s3 cp "s3://infrastructure-as-code-invictus/terraform/terraform-$(terraformVersion)" "terraform"
+
+          # Validar que el archivo se descargó
+          if [ ! -s terraform ]; then
+            echo "❌ Error: No se pudo descargar terraform: $(terraformVersion)"
+            exit 99
+          fi
+
+          # Hacerlo ejecutable y moverlo
+          chmod +x terraform
+          sudo mv terraform /usr/local/bin/terraform
+
+          echo -e "\n🚀 Terraform instalado correctamente:"
+          terraform --version
+        displayName: "Instalar terraform"
+        env:
+          AWS_ACCESS_KEY_ID: $(ACCOUNT_ID_DEPLOY)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      # - script: |
+      #     sudo apt-get update -y
+      #     sudo apt-get install -y unzip
+      #     curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/$(terragruntVersion)/terragrunt_linux_amd64
+      #     chmod +x terragrunt_linux_amd64
+      #     sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
+      #     terragrunt --version
+      #   displayName: "Instalar Terragrunt"
+      #   env:
+      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      # - script: |
+      #     sudo apt-get update -y
+      #     sudo apt-get install -y unzip
+      #     curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/$(terragruntVersion)/terragrunt_linux_amd64
+      #     chmod +x terragrunt_linux_amd64
+      #     sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
+      #     terragrunt --version
+      #   displayName: "Instalar Terragrunt"
+      #   env:
+      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
       
       # - task: replacetokens@5
       #   inputs:
@@ -63,22 +120,22 @@ jobs:
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
       
-      - script: |
-          echo "apply"
-          terragrunt run-all apply --terragrunt-non-interactive
-        displayName: "apply"
-        workingDirectory: $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/develop/apps/aws-service-cloudfront/cloudfront-app-administration
-        env:
-          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
-          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
-          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+      # - script: |
+      #     echo "apply"
+      #     terragrunt run-all apply --terragrunt-non-interactive
+      #   displayName: "apply"
+      #   workingDirectory: $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/develop/apps/aws-service-cloudfront/cloudfront-app-administration
+      #   env:
+      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
+      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
+      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
       
-      - script: |
-          echo "destroy"
-          terragrunt run-all destroy --terragrunt-non-interactive
-        displayName: "destroy"
-        workingDirectory: $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/develop/apps/aws-service-cloudfront/cloudfront-app-administration
-        env:
-          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
-          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
-          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+      # - script: |
+      #     echo "destroy"
+      #     terragrunt run-all destroy --terragrunt-non-interactive
+      #   displayName: "destroy"
+      #   workingDirectory: $(Build.SourcesDirectory)/iac-terragrunt/project/invictus/develop/apps/aws-service-cloudfront/cloudfront-app-administration
+      #   env:
+      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
+      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
+      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
