Updates

diff --git a/pipeline/build/jobs/job-frontend.yml b/pipeline/build/jobs/job-frontend.yml
--- a/pipeline/build/jobs/job-frontend.yml
+++ b/pipeline/build/jobs/job-frontend.yml
@@ -176,7 +176,7 @@ jobs:
             echo "✅ Dependencias Instaladas:"
             echo "$OUTPUT"
           fi
-        displayName: "📦 Install Microservice Dependencies"
+        displayName: "📦 Install MicroFrontend Dependencies"
 
 
       - script: |
@@ -187,13 +187,21 @@ jobs:
             msName=${msName%-vue2}
             echo "Name MS:$msName"
             npm run build
-            ls -la $(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist
           else
             pnpm add -D dotenv-cli
             pnpm build --filter=...$(msName)
-            ls -la $(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist
           fi
-        displayName: "🛠️ Build Microservice $(msName)"
+
+          DIST_PATH="$(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist"
+
+          if [[ ! -d "$DIST_PATH" ]] || [[ -z "$(ls -A "$DIST_PATH" 2>/dev/null)" ]]; then
+            echo "❌ Error: No se generó el build o la carpeta dist está vacía."
+            exit 1
+          else
+            echo "✅ Build generado correctamente en $DIST_PATH"
+            ls -la "$DIST_PATH"
+          fi
+        displayName: "🛠️ Build MicroFrontend $(msName)"
 
       - script: |
           echo "Descomentando app-legacy/*"
@@ -344,6 +352,7 @@ jobs:
             aws s3 cp ./$(file)/$(msName)/dist s3://mf-prueba-$msName-$(ACCOUNT_ID_INVIC)/$(msVersion)/ --recursive
           else
             echo "No se encontro la carpeta dist, por ende no compilo el proyecto $msName"
+            exit 1
           fi
         displayName: "⚡ Upload Files to S3 Bucket"
         condition: and(
