feat: refactor flutter

diff --git a/pipeline/ci/build/build-flutter.yml b/pipeline/ci/build/build-flutter.yml
--- a/pipeline/ci/build/build-flutter.yml
+++ b/pipeline/ci/build/build-flutter.yml
@@ -249,26 +249,56 @@ jobs:
           targetType: inline
           script: |
             set -e
-            echo -e "\nℹ️ Validando Build Apk..."
+            echo -e "\nℹ️ Validando Build APK..."
 
-            if [[ -d "build/app/outputs/flutter-apk" ]] && [[ "$(ls -A build/app/outputs/flutter-apk)" ]]; then
-              echo -e "\n✅ Apk encontrado"
+            APK_PATH="build/app/outputs/flutter-apk/app-profile.apk"
+            SHA1_PATH="build/app/outputs/flutter-apk/app-profile.apk.sha1"
+
+            if [[ -f "$APK_PATH" && -f "$SHA1_PATH" ]]; then
+              echo -e "\n✅ APK encontrado"
               echo "📁 Files: build/app/outputs/flutter-apk"
               ls -la build/app/outputs/flutter-apk
 
-              SHA1_APK=$(shasum -a 1 build/app/outputs/flutter-apk/app-profile.apk | awk '{print $1}')
-              SHA1_FLUTTER=$(cut -d ' ' -f1 build/app/outputs/flutter-apk/app-profile.apk.sha1)
+              SHA1_APK=$(cut -d ' ' -f1 "$SHA1_PATH")
+              SHA256_APK=$(shasum -a 256 "$APK_PATH" | awk '{print $1}')
               APKSIGNER=$(find "$ANDROID_HOME/build-tools" -name apksigner -type f | sort -V | tail -1)
+              CERTIFICATE_INFO=$("$APKSIGNER" verify --print-certs "$APK_PATH")
 
-              echo -e "\n🔐 SHA-1 Apk: $SHA1_APK"
-              echo "🔐 SHA-1 Flutter: $SHA1_FLUTTER"
-              echo "🔐 SHA-1 Certificado:"
-              "$APKSIGNER" verify --print-certs build/app/outputs/flutter-apk/app-profile.apk
+              echo "##vso[task.setvariable variable=SHA1_APK]$SHA1_APK"
+              echo "##vso[task.setvariable variable=SHA256_APK]$SHA256_APK"
+
+              echo -e "\nℹ️ Informacion del APK..."
+              echo "🔐 SHA-1 APK    : $SHA1_APK"
+              echo "🔐 SHA-256 APK  : $SHA256_APK"
+              echo -e "🔐 Firma digital: $CERTIFICATE_INFO"
             else
-              echo -e "\n##vso[task.logissue type=error]⚠️ Error: Apk no encontrado"
+              echo -e "\n##vso[task.logissue type=error]⚠️ Error: APK o SHA-1 no encontrado"
               exit 99
             fi
         displayName: "🔎 Validate Build"
+        condition: succeeded()
+
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            jq --arg version "$(version)" \
+              --arg apk "$(APK_URL)" \
+              --arg sha256 "$(SHA256_APK)" \
+              --arg releaseNotes "Nuevas features y fixes" \
+              --arg cleanCache "false" \
+              '.version = $version |
+                .apkUrl = $apk |
+                .sha256checksum = $sha256 |
+                .releaseNotes = $releaseNotes |
+                .cleanCache = $cleanCache' \
+              version.json > tmp.json && mv tmp.json version.json
+
+            echo -e "\n📁 File: version.json"
+            ls -la version.json
+            cat version.json
+        displayName: "⚙️ Generate version.json"
         condition: succeeded()
 
       - task: Bash@3
@@ -281,14 +311,9 @@ jobs:
             mv build/app/outputs/flutter-apk/app-profile.apk build/app/outputs/flutter-apk/invictus-$(environment)-$(version).apk
             mv build/app/outputs/flutter-apk/app-profile.apk.sha1 build/app/outputs/flutter-apk/invictus-$(environment)-$(version).apk.sha1
 
-
-            echo -e "\n🌳 Estructura del proyecto:"
-            find . -maxdepth 5 -type f | sort
-
-
-
             mkdir -p "$(Build.ArtifactStagingDirectory)/release/$(environment)"
-            cp -R build/app/outputs/flutter-apk/* $(Build.ArtifactStagingDirectory)/release/$(environment)/
+            cp -f version.json "$(Build.ArtifactStagingDirectory)/release/$(environment)/"
+            cp -R build/app/outputs/flutter-apk/* "$(Build.ArtifactStagingDirectory)/release/$(environment)/"
 
             echo -e "\n📁 Files: build/app/outputs/flutter-apk"
             ls -l build/app/outputs/flutter-apk
