Test files

diff --git a/pipeline/ci/build/build-electron.yml b/pipeline/ci/build/build-electron.yml
--- a/pipeline/ci/build/build-electron.yml
+++ b/pipeline/ci/build/build-electron.yml
@@ -13,10 +13,22 @@ jobs:
         parameters:
           region: ${{ parameters.region }}
 
+    strategy:
+      matrix:
+        ${{ each region in parameters.region }}:
+          ${{ region }}:
+            regionName: ${{ region }}
+
     steps:
       - checkout: electron
         fetchDepth: 0
         persistCredentials: true
+
+      - task: DownloadBuildArtifacts@0
+        inputs:
+          artifactName: "versions"
+          downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
+        displayName: "📥 Download Version Artifact"
 
       - task: DownloadPipelineArtifact@2
         inputs:
@@ -24,18 +36,18 @@ jobs:
           path: $(Pipeline.Workspace)/downloaded-dists
         displayName: "📥 Download Dist Files"
 
-      # - ${{ each app in parameters.apps }}:
-      #     - task: DownloadPipelineArtifact@2
-      #       inputs:
-      #         artifact: build-${{ app }}
-      #         path: $(Pipeline.Workspace)/builds/${{ app }}
-      #       displayName: "📥 Descargar build-${{ app }}"
+      - script: |
+          DISTS_PATH="$(Pipeline.Workspace)/downloaded-dists/${{ parameters.region }}"
+          DISTS_COUNT=$(ls $DISTS_PATH | wc -l)
 
-      - task: DownloadBuildArtifacts@0
-        inputs:
-          artifactName: "versions"
-          downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
-        displayName: "📥 Download Version Artifact"
+          if [[ "$DISTS_COUNT" == "1" ]]; then
+            echo -e "\n📁 Dists generados correctamente en: $DIST_PATH "
+            ls -la "$DIST_PATH"
+          else
+            echo -e "\n⚠️ Error no tiene exactamente todos los dists en: $DIST_PATH "
+            exit 99
+          fi
+        displayName: "🔎 Validate downloaded dists"
 
       - script: |
           echo -e "\nℹ️ Pipeline branch: $(Build.SourceBranch)"
@@ -52,4 +64,12 @@ jobs:
             echo -e "\n##vso[task.logissue type=error]❌ No se encontro archivo de versión para $(Build.Repository.Name)"
             exit 99
           fi
-        displayName: "📚 Read version"
+        displayName:
+          "📚 Read version"
+
+          # DIST_PATH="$(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist"
+
+          # DIST_COUNT="$(System.DefaultWorkingDirectory)/$(file)/$(msName)"
+          # DIST_COUNT=$(ls "$DIST_PATH" | wc -l)
+
+          # if [ "$FILE_COUNT" -ne 2 ]; then
