Update files

diff --git a/pipeline/ci/build/build-electron.yml b/pipeline/ci/build/build-electron.yml
--- a/pipeline/ci/build/build-electron.yml
+++ b/pipeline/ci/build/build-electron.yml
@@ -72,25 +72,44 @@ jobs:
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
       - script: |
-          echo -e "\nℹ️ Creando archivo .env..." 
-          echo "Electron Branch: $(electronBranch)"
-          echo "Electron Environment: $(environment)"
+          CURRENT_BRANCH="$(Build.SourceBranch)"
+          environment="unknown"
 
-          envPath="$(System.DefaultWorkingDirectory)/.env"
-          cat <<EOF > $envPath
+          case "$CURRENT_BRANCH" in
+            refs/heads/feature/*) environment="dev"; ;;
+            refs/heads/develop)   environment="dev"; ;;
+            refs/heads/staging)   environment="qa"; ;;
+            refs/heads/master) 
+              case "$red" in
+                "antioquia") environment="matrixtech"; ;;
+                "cap")       environment="cap"; ;;
+                "tolima")    environment="seapto"; ;;
+                "huila")     environment="suchance"; ;;
+                "cauca")     environment="acertemos"; ;;
+                "boyaca")    environment="jer"; ;;
+                "santander") environment="laperla"; ;;
+              esac ;;
+          esac
+
+          if [[ "$environment" = "unknown" ]]; then
+            echo -e "\n##vso[task.logissue type=error]⚠️ Environment [$environment] no reconocido"
+            exit 99
+          fi
+
+          cat <<EOF > .env
           DOMAIN_ADMIN="${BASE_URL_ELECTRON_ADMIN}"
           DOMAIN_SELLER="${BASE_URL_ELECTRON_SELLERS}"
           TARGET="linux"
-          TARGET_ENVIRONMENT="$(environment)"
+          TARGET_ENVIRONMENT="$environment"
           EOF
 
+          echo "##vso[task.setvariable variable=environment]$environment"
           echo -e "\n✅ Archivo .env creado correctamente"
-          ls -la $(System.DefaultWorkingDirectory)
-
-          echo -e "\n📁 Generando .env"
-          cat $envPath
+          cat .env
         displayName: "⚙️ Generate .env"
         condition: succeeded()
+        env:
+          red: ${{ parameters.red }}
 
       - task: UsePythonVersion@0
         displayName: "🔧 Use Python $(pythonVersion)"
@@ -296,25 +315,47 @@ jobs:
         inputs:
           targetType: "inline"
           script: |
-            Write-Host "`nℹ️ Creando archivo .env..."
-            Write-Host "Electron Branch: $($env:electronBranch)" 
-            Write-Host "Electron Environment: $($env:environment)"
+            $ErrorActionPreference = "Stop"
+            Write-Host "`n📁 Generando .env"
 
-            $envPath = "$(System.DefaultWorkingDirectory)/.env"
-            $envContent = @"
+            $currentBranch="$(Build.SourceBranch)"
+            $environment = "unknown"
+
+            switch -Wildcard ($currentBranch) {
+              "refs/heads/feature/*" { $environment = "dev"; break }
+              "refs/heads/develop"   { $environment = "dev"; break }
+              "refs/heads/staging"   { $environment = "qa"; break }
+              "refs/heads/master" {
+                switch ($env:red) {
+                  "antioquia" { $environment = "matrixtech"; break }
+                  "cap"       { $environment = "cap"; break }
+                  "tolima"    { $environment = "seapto"; break }
+                  "huila"     { $environment = "suchance"; break }
+                  "cauca"     { $environment = "acertemos"; break }
+                  "boyaca"    { $environment = "jer"; break }
+                  "santander" { $environment = "laperla"; break }
+                }
+              }
+            }
+
+            if ($environment -ne "unknown") {
+            @"
             DOMAIN_ADMIN="$(BASE_URL_ELECTRON_ADMIN)"
             DOMAIN_SELLER="$(BASE_URL_ELECTRON_SELLERS)"
             TARGET="windows"
-            TARGET_ENVIRONMENT="$($env:environment)"
-            "@
-            Set-Content -Path $envPath -Value $envContent -Encoding UTF8
-
-            Write-Host "`n✅ Archivo .env creado correctamente"
-            Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
-
-            Write-Host "`n📁 Generando .env"
-            Get-Content -Path $envPath
+            TARGET_ENVIRONMENT="$environment"
+            "@ | Set-Content -Encoding UTF8 .env
+              
+              Write-Host "##vso[task.setvariable variable=environment]$environment"
+              Write-Host "`n✅ Archivo .env creado correctamente"
+              Get-Content .env
+            } else {
+              Write-Host "`n❌ No se encontro una rama valida, branch [$environment]."
+              exit 99
+            }
         condition: succeeded()
+        env:
+          red: ${{ parameters.red }}
 
       - task: UsePythonVersion@0
         displayName: "🔧 Use Python $(pythonVersion)"
