Update file

diff --git a/pipeline/ci/build/build-electron.yml b/pipeline/ci/build/build-electron.yml
--- a/pipeline/ci/build/build-electron.yml
+++ b/pipeline/ci/build/build-electron.yml
@@ -35,7 +35,8 @@ jobs:
             exit 99
           fi
 
-          echo "##vso[task.setvariable variable=electronBranch]$electronBranch"
+          echo "##vso[task.setvariable variable=electronBranch]feature/security-vulnerability-refactor"
+          #echo "##vso[task.setvariable variable=electronBranch]$electronBranch"
           echo ""
           echo "ℹ️ Branch Actual: $CURRENT_BRANCH"
           echo "ℹ️ Branch Checkout: $electronBranch"
@@ -44,14 +45,9 @@ jobs:
 
       - script: |
           echo -e "\n🔀 Cambiando a la rama: electron@$(electronBranch)"
-          # git fetch origin $(electronBranch)
-          # git checkout $(electronBranch)
-          # git pull origin $(electronBranch)
-
-          git fetch origin feature/security-vulnerability-refactor
-          git checkout feature/security-vulnerability-refactor
-          git pull origin feature/security-vulnerability-refactor
-
+          git fetch origin $(electronBranch)
+          git checkout $(electronBranch)
+          git pull origin $(electronBranch)
         displayName: "🔄 Checkout electron@$(electronBranch)"
         condition: and(succeeded(), eq(${{ parameters.microFronted }}, true))
 
@@ -96,7 +92,7 @@ jobs:
             echo -e "\n⚠️ Error no tiene exactamente todos los dists en: $DISTS_PATH"
             exit 99
           fi
-        displayName: "🔎 Validate and Copy Dists "
+        displayName: "🔎 Validate and Copy Dists"
 
       - task: Bash@3
         name: AuthCodeArtifact
@@ -273,10 +269,357 @@ jobs:
 
           echo -e "\n✅ Archivos subidos exitosamente."
           echo "🔗 APP: InvictusUX-$(msVersion).AppImage"
-          echo "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/linux/$(environment)/InvictusUX-$(msVersion).AppImage"
+          #echo "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/linux/$(environment)/InvictusUX-$(msVersion).AppImage"
+          echo "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/linux/dev-test/$(environment)/InvictusUX-$(msVersion).AppImage"
 
         displayName: "📤 Upload Bucket S3"
         #condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
+        env:
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+  #
+  # Electron Windows
+  #
+  - job: build_electron_windows
+    displayName: "📦 build electron"
+    pool:
+      name: "Azure Pipelines"
+      vmImage: "windows-latest"
+
+    variables:
+      - template: ../../variables/groups-transversal-variables-electron.yml
+        parameters:
+          region: ${{ parameters.region }}
+
+    steps:
+      - checkout: electron
+        fetchDepth: 0
+        persistCredentials: true
+
+      - task: PowerShell@2
+        displayName: "📌 Set Electron Branch"
+        inputs:
+          targetType: "inline"
+          script: |
+            $CURRENT_BRANCH = "$(Build.SourceBranch)"
+            $electronBranch = "unknown"
+
+            switch -Wildcard ($CURRENT_BRANCH) {
+              "refs/heads/feature/*" { $electronBranch = "develop" }
+              "refs/heads/hotfix/*"  { $electronBranch = "develop" }
+              "refs/heads/develop"   { $electronBranch = "develop" }
+              "refs/heads/staging"   { $electronBranch = "staging" }
+              "refs/heads/master"    { $electronBranch = "master" }
+            }
+
+            if ($electronBranch -eq "unknown") {
+              Write-Host "`n⚠️ Electron Branch [$electronBranch] no reconocida"
+              exit 99
+            }
+
+            Write-Host "##vso[task.setvariable variable=electronBranch]feature/security-vulnerability-refactor"
+            #Write-Host "##vso[task.setvariable variable=electronBranch]$electronBranch"
+            Write-Host ""
+            Write-Host "ℹ️ Branch Actual: $CURRENT_BRANCH"
+            Write-Host "ℹ️ Branch Checkout: $electronBranch"
+        condition: and(succeeded(), eq(${{ parameters.microFronted }}, true))
+
+      - task: PowerShell@2
+        displayName: "🔄 Checkout electron@$(electronBranch)"
+        inputs:
+          targetType: "inline"
+          script: |
+            Write-Host "`n🔀 Cambiando a la rama: electron@$(electronBranch)"
+            git fetch origin $($env:environment)
+            git checkout $($env:environment)
+            git pull origin $($env:environment)
+        condition: and(succeeded(), eq(${{ parameters.microFronted }}, true))
+
+      - task: DownloadBuildArtifacts@0
+        displayName: "📥 Download Version"
+        inputs:
+          artifactName: "versions"
+          downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
+
+      - task: PowerShell@2
+        displayName: "📚 Read version"
+        inputs:
+          targetType: "inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            $versionFile = "$(Pipeline.Workspace)\downloaded-versions\versions\electron\version.json"
+            if (Test-Path $versionFile) {
+              $json = Get-Content $versionFile | ConvertFrom-Json
+              $version = $json.version
+              $baseVersion = $version.Split('-')[0]
+              Write-Host "`n🚀 Versión detectada para .exe: $baseVersion"
+              Write-Host "##vso[task.setvariable variable=version]$baseVersion"
+            } else {
+              Write-Host "`n❌ No se encontro archivo de versión para .exe"
+              exit 99
+            }
+
+      - task: DownloadBuildArtifacts@0
+        displayName: "📥 Download Dists"
+        inputs:
+          artifactName: "dists"
+          downloadPath: "$(Pipeline.Workspace)/downloaded-dists"
+
+      - task: PowerShell@2
+        displayName: "🔎 Validate and Copy Dists"
+        inputs:
+          targetType: "inline"
+          script: |
+            $DISTS_PATH = "$(Pipeline.Workspace)\downloaded-dists\${{ parameters.region }}"
+            $DEST_PATH = "$(System.DefaultWorkingDirectory)\apps"
+
+            if (-Not (Test-Path $DISTS_PATH)) {
+              Write-Host "`n❌ El directorio $DISTS_PATH no existe"
+              exit 99
+            }
+
+            $DISTS_COUNT = (Get-ChildItem -Path $DISTS_PATH | Measure-Object).Count
+
+            if ($DISTS_COUNT -eq 1) {
+              Write-Host "`n✅ Se encontró 1 dist. Copiando a: $DEST_PATH"
+              Copy-Item -Path "$DISTS_PATH\*" -Destination $DEST_PATH -Recurse -Force
+
+              Write-Host "`n📁 Dists copiados en: $DEST_PATH"
+              Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" | Format-List
+              Write-Host "`n📁 Dists apps"
+              Get-ChildItem -Path "$DEST_PATH" | Format-List
+            }
+            else {
+              Write-Host "`n⚠️ Error: Se esperaban exactamente 1 dist, pero se encontraron $DISTS_COUNT en: $DISTS_PATH"
+              exit 99
+            }
+
+      - task: PowerShell@2
+        displayName: "🔐 Setup CodeArtifact & npm config"
+        inputs:
+          targetType: "inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            Write-Host "🔐 Obteniendo token de AWS CodeArtifact..."
+
+            $token = aws codeartifact get-authorization-token `
+              --domain matrixtech-npm-repository `
+              --domain-owner $env:ACCOUNT_ID_DEPLOY `
+              --region $env:AWS_DEFAULT_REGION `
+              --query authorizationToken `
+              --output text
+
+            if (-not $token) {
+              Write-Error "`n❌ No se pudo obtener el token de AWS CodeArtifact"
+              exit 99
+            }
+
+            $repoDomain = "matrixtech-npm-repository-$($env:ACCOUNT_ID_DEPLOY).d.codeartifact.$($env:AWS_DEFAULT_REGION).amazonaws.com"
+            $repoPath = "npm/matrixtech-npm-repository"
+            $repoUrl = "https://$repoDomain/$repoPath"
+
+            Write-Host "Configurando npm..."
+            npm config set "//$repoDomain/$repoPath/:_authToken" $token
+            npm config set registry $repoUrl
+
+            Write-Host "Verificando identidad de AWS..."
+            aws sts get-caller-identity
+
+            $npmrcPath = Join-Path "$(System.DefaultWorkingDirectory)" ".npmrc"
+            @"
+            //$repoDomain/$repoPath/:_authToken=$token
+            registry=$repoUrl
+            "@ | Set-Content -Encoding UTF8 -Path $npmrcPath
+
+            Write-Host "`n✅ Archivo .npmrc creado correctamente"
+            Get-Item $npmrcPath | Select-Object Name, FullName, Length, LastWriteTime, Mode
+        env:
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      - task: PowerShell@2
+        displayName: "⚙️ Generate .env"
+        inputs:
+          targetType: "inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            Write-Host "`n📁 Generando .env"
+
+            $currentBranch="$(Build.SourceBranch)"
+            $environment = "unknown"
+            $region = "unknown"
+
+            switch -Wildcard ($currentBranch) {
+              "refs/heads/feature/*" { $environment = "dev"; $region = "dev"; }
+              "refs/heads/develop"   { $environment = "dev"; $region = "dev"; }
+              "refs/heads/staging"   { $environment = "qa";  $region = "qa"; }
+              "refs/heads/master" {
+                switch ($env:red) {
+                  "antioquia" { $environment = "production"; $region = "matrixtech"; }
+                  "cap"       { $environment = "production"; $region = "cap"; }
+                  "tolima"    { $environment = "production"; $region = "seapto"; }
+                  "huila"     { $environment = "production"; $region = "suchance"; }
+                  "cauca"     { $environment = "production"; $region = "acertemos"; }
+                  "boyaca"    { $environment = "production"; $region = "jer"; }
+                }
+              }
+            }
+
+            if ($environment -ne "unknown") {
+            @"
+            DOMAIN_ADMIN="$(BASE_URL_ELECTRON_ADMIN)"
+            DOMAIN_SELLER="$(BASE_URL_ELECTRON_SELLERS)"
+            TARGET="windows"
+            TARGET_ENVIRONMENT="$environment"
+            "@ | Set-Content -Encoding UTF8 .env
+              
+              Write-Host "##vso[task.setvariable variable=environment]$environment"
+              Write-Host "##vso[task.setvariable variable=region]$region"
+              Write-Host "`n✅ Archivo .env creado correctamente"
+              Get-Content .env
+            } else {
+              Write-Host "`n❌ No se encontro una rama valida, branch [$environment]."
+              exit 99
+            }
+        env:
+          red: ${{ parameters.red }}
+
+      - task: UsePythonVersion@0
+        displayName: "🔧 Use Python $(versionPython)"
+        inputs:
+          versionSpec: "$(versionPython)"
+          addToPath: true
+
+      - task: NodeTool@0
+        displayName: "🔧 Install Nodejs $(versionNode)"
+        inputs:
+          versionSource: "spec"
+          versionSpec: "$(versionNode)"
+
+      - task: PowerShell@2
+        displayName: "📝 Update version in package.json"
+        inputs:
+          targetType: "inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            Write-Host "📦 Modificando versión en package.json: $env:version"
+            $packagePath = "$(Build.SourcesDirectory)\package.json"
+
+            if (Test-Path $packagePath) {
+              $packageJson = Get-Content $packagePath -Raw | ConvertFrom-Json
+              $packageJson.version = $env:version
+              $packageJson | ConvertTo-Json -Depth 10 | Set-Content -Encoding UTF8 $packagePath
+
+              Write-Host "`n✅ Version en package.json actualizada correctamente."
+              Get-Content $packagePath | ForEach-Object { Write-Host $_ }
+            } else {
+              Write-Host "`n❌ No se encontro el archivo package.json en la ruta [$packagePath]"
+              exit 99
+            }
+
+      - task: PowerShell@2
+        displayName: "🧹 Remove BOM from package.json"
+        inputs:
+          targetType: "inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            $filePath = "$(Build.SourcesDirectory)\package.json"
+
+            if (Test-Path $filePath) {
+                $bytes = [System.IO.File]::ReadAllBytes($filePath)
+                if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
+                    [System.IO.File]::WriteAllBytes($filePath, $bytes[3..($bytes.Length-1)])
+                    Write-Host "`n⚠️ BOM removed from package.json"
+                } else {
+                    Write-Host "`n✅ package.json no contiene BOM"
+                }
+            } else {
+                Write-Warning "`n❌ package.json no se encontró en $filePath"
+                exit 99
+            }
+
+      - task: PowerShell@2
+        displayName: "⚙️ Install dependencies"
+        inputs:
+          targetType: "inline"
+          script: |
+            Write-Host "📦 Instalando dependencias"
+            npm install
+
+            Write-Host "`n📦 Dependencias instaladas:"
+            npm list --depth=0
+
+      - task: PowerShell@2
+        displayName: "📦 Build electron"
+        inputs:
+          targetType: " inline"
+          script: |
+            Write-Host "📦 Ejecutando build..."
+            npm run build
+
+      - task: PowerShell@2
+        displayName: "🔍 Validate Build"
+        inputs:
+          targetType: " inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            Write-Host "📝 Validando build electron..."
+
+            $basePath = "$(Build.SourcesDirectory)\release\$($env:environment)\$($env:version)"
+            New-Item -ItemType Directory -Path $basePath\$($env:region) -Force | Out-Null
+            $allFound = $true 
+
+            $filesToCopy = @(
+              "InvictusUX Setup $($env:version).exe",
+              "InvictusUX Setup $($env:version).exe.blockmap",
+              "latest.yml"
+            )
+
+            foreach ($file in $filesToCopy) {
+              $sourcePath      = Join-Path "$basePath" $file
+              $destinationPath = Join-Path "$basePath\$($env:region)" $file
+
+              if (Test-Path $sourcePath) {
+                Copy-Item -Path $sourcePath -Destination $destinationPath -Force
+                Write-Host "📂 Copiado: $file -> $destinationPath"
+              } else {
+                Write-Host "⚠️ Archivo no encontrado $file -> $sourcePath"
+                $allFound = $false
+              }
+            }
+
+            if (-not $allFound) {
+              Write-Error "`n❌ Error: archivos requeridos no encontrados."
+              exit 99
+            } else {
+              Write-Host "`n📂 Directorio: $basePath\$($env:region)"
+              Get-ChildItem "$basePath\$($env:region)" -Force | Select-Object Mode, LastWriteTime, Length, Name | Format-Table -AutoSize
+            }
+
+      - task: PowerShell@2
+        displayName: "📤 Upload Bucket S3"
+        inputs:
+          targetType: " inline"
+          script: |
+            $ErrorActionPreference = "Stop"
+            Write-Host "📦 Cargando al Bucket S3..."
+
+            $basePath = "$(Build.SourcesDirectory)\release\$($env:environment)\$($env:version)\$($env:region)"
+            Write-Host "`n📂 Archivos a cargar: $basePath"
+            Get-ChildItem "$basePath" -Force | Select-Object Mode, LastWriteTime, Length, Name | Format-Table -AutoSize
+
+            #aws s3 cp "$basePath" "s3://e-remote/invictus-electron/windows/$($env:region)" --recursive --acl public-read
+            aws s3 cp "$basePath" "s3://e-remote/invictus-electron/windows/dev-test/$($env:region)" --recursive --acl public-read
+
+            Write-Host "`n✅ Archivos subidos exitosamente."
+            Write-Host "🔗 APP: InvictusUX Setup $($env:version).exe"
+            #Write-Host "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/windows/$($env:environment)/InvictusUX+Setup+$($env:version).exe"
+            Write-Host "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/windows/dev-test/$($env:environment)/InvictusUX+Setup+$($env:version).exe"
+
+        condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
         env:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
