Update files

diff --git a/pipeline/ci/build/build-electron.yml b/pipeline/ci/build/build-electron.yml
--- a/pipeline/ci/build/build-electron.yml
+++ b/pipeline/ci/build/build-electron.yml
@@ -82,24 +82,24 @@ jobs:
         displayName: "📥 Download Dists"
         condition: succeeded()
 
-      # - script: |
-      #     DISTS_PATH="$(Pipeline.Workspace)/downloaded-dists/${{ parameters.region }}"
-      #     DISTS_COUNT=$(ls "$DISTS_PATH" | wc -l)
+      - script: |
+          DISTS_PATH="$(Pipeline.Workspace)/downloaded-dists/${{ parameters.region }}"
+          DISTS_COUNT=$(ls "$DISTS_PATH" | wc -l)
 
-      #     if [[ "$DISTS_COUNT" == "15" ]]; then
-      #       cp -R $DISTS_PATH $(System.DefaultWorkingDirectory)/apps
+          if [[ "$DISTS_COUNT" == "15" ]]; then
+            cp -R $DISTS_PATH $(System.DefaultWorkingDirectory)/apps
 
-      #       echo -e "\n📁 Dists copiados en: $(System.DefaultWorkingDirectory)/apps"
-      #       ls -l $(System.DefaultWorkingDirectory)
-      #       echo -e "\n📁 Dists apps"
-      #       ls -l $(System.DefaultWorkingDirectory)/apps
-      #     else
-      #       echo -e "\n⚠️ Error no tiene exactamente todos los dists en: $DISTS_PATH"
-      #       ls -l $(System.DefaultWorkingDirectory)/apps
-      #       exit 99
-      #     fi
-      #   displayName: "🔎 Validate and Copy Dists"
-      #   condition: succeeded()
+            echo -e "\n📁 Dists copiados en: $(System.DefaultWorkingDirectory)/apps"
+            ls -l $(System.DefaultWorkingDirectory)
+            echo -e "\n📁 Dists apps"
+            ls -l $(System.DefaultWorkingDirectory)/apps
+          else
+            echo -e "\n⚠️ Error no tiene exactamente todos los dists en: $DISTS_PATH"
+            ls -l $(System.DefaultWorkingDirectory)/apps
+            exit 99
+          fi
+        displayName: "🔎 Validate and Copy Dists"
+        condition: succeeded()
 
       - task: Bash@3
         name: AuthCodeArtifact
@@ -377,28 +377,28 @@ jobs:
           downloadPath: "$(Pipeline.Workspace)/downloaded-dists"
         condition: succeeded()
 
-      # - task: PowerShell@2
-      #   displayName: "🔎 Validate and Copy Dists"
-      #   inputs:
-      #     targetType: "inline"
-      #     script: |
-      #       $DISTS_PATH = "$(Pipeline.Workspace)\downloaded-dists\dists\${{ parameters.region }}"
-      #       $DISTS_COUNT = (Get-ChildItem -Path $DISTS_PATH).Count
+      - task: PowerShell@2
+        displayName: "🔎 Validate and Copy Dists"
+        inputs:
+          targetType: "inline"
+          script: |
+            $DISTS_PATH = "$(Pipeline.Workspace)\downloaded-dists\dists\${{ parameters.region }}"
+            $DISTS_COUNT = (Get-ChildItem -Path $DISTS_PATH).Count
 
-      #       if ($DISTS_COUNT -eq 15) {
-      #         New-Item -Path $(System.DefaultWorkingDirectory)\apps -ItemType Directory | Out-Null
-      #         Copy-Item -Path "$DISTS_PATH\*" -Destination "$(System.DefaultWorkingDirectory)\apps" -Recurse -Force
+            if ($DISTS_COUNT -eq 15) {
+              New-Item -Path $(System.DefaultWorkingDirectory)\apps -ItemType Directory | Out-Null
+              Copy-Item -Path "$DISTS_PATH\*" -Destination "$(System.DefaultWorkingDirectory)\apps" -Recurse -Force
 
-      #         Write-Host "`n📁 Dists copiados en: $(System.DefaultWorkingDirectory)\apps"
-      #         Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
-      #         Write-Host "`n📁 Dists apps"
-      #         Get-ChildItem -Path "$(System.DefaultWorkingDirectory)\apps" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
-      #       } else {
-      #         Write-Host "`n⚠️ Error no tiene exactamente todos los dists en: $DISTS_PATH"
-      #         Get-ChildItem -Path "$(System.DefaultWorkingDirectory)\apps" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
-      #         exit 99
-      #       }
-      #   condition: succeeded()
+              Write-Host "`n📁 Dists copiados en: $(System.DefaultWorkingDirectory)\apps"
+              Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
+              Write-Host "`n📁 Dists apps"
+              Get-ChildItem -Path "$(System.DefaultWorkingDirectory)\apps" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
+            } else {
+              Write-Host "`n⚠️ Error no tiene exactamente todos los dists en: $DISTS_PATH"
+              Get-ChildItem -Path "$(System.DefaultWorkingDirectory)\apps" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
+              exit 99
+            }
+        condition: succeeded()
 
       - task: PowerShell@2
         displayName: "🔐 Setup CodeArtifact & npm config"
