feat: optimización front

diff --git a/pipeline/ci/build/build-frontend.yml b/pipeline/ci/build/build-frontend.yml
--- a/pipeline/ci/build/build-frontend.yml
+++ b/pipeline/ci/build/build-frontend.yml
@@ -56,168 +56,168 @@ jobs:
         displayName: "📂 Select Directory"
         condition: succeeded()
 
-      # - task: Bash@3
-      #   name: AuthCodeArtifact
-      #   inputs:
-      #     targetType: "inline"
-      #     script: |
-      #       echo "🔐 Obteniendo token de AWS CodeArtifact..."
-      #       token=$(aws codeartifact get-authorization-token \
-      #         --domain matrixtech-npm-repository \
-      #         --domain-owner "$ACCOUNT_ID_DEPLOY" \
-      #         --region "$AWS_DEFAULT_REGION" \
-      #         --query authorizationToken \
-      #         --output text)
+      - task: Bash@3
+        name: AuthCodeArtifact
+        inputs:
+          targetType: "inline"
+          script: |
+            echo "🔐 Obteniendo token de AWS CodeArtifact..."
+            token=$(aws codeartifact get-authorization-token \
+              --domain matrixtech-npm-repository \
+              --domain-owner "$ACCOUNT_ID_DEPLOY" \
+              --region "$AWS_DEFAULT_REGION" \
+              --query authorizationToken \
+              --output text)
 
-      #       REPO_DOMAIN="matrixtech-npm-repository-$ACCOUNT_ID_DEPLOY.d.codeartifact.$AWS_DEFAULT_REGION.amazonaws.com"
-      #       REPO_PATH="npm/matrixtech-npm-repository"
-      #       REPO_URL="https://$REPO_DOMAIN/$REPO_PATH"
+            REPO_DOMAIN="matrixtech-npm-repository-$ACCOUNT_ID_DEPLOY.d.codeartifact.$AWS_DEFAULT_REGION.amazonaws.com"
+            REPO_PATH="npm/matrixtech-npm-repository"
+            REPO_URL="https://$REPO_DOMAIN/$REPO_PATH"
 
-      #       echo "Configurando npm..."
-      #       npm config set "//$REPO_DOMAIN/$REPO_PATH/:_authToken" "$token"
-      #       npm config set registry "$REPO_URL"
+            echo "Configurando npm..."
+            npm config set "//$REPO_DOMAIN/$REPO_PATH/:_authToken" "$token"
+            npm config set registry "$REPO_URL"
 
-      #       echo "Verificando identidad de AWS..."
-      #       aws sts get-caller-identity
+            echo "Verificando identidad de AWS..."
+            aws sts get-caller-identity
 
-      #       npmrcPath="$(file)/$(msName)/.npmrc"
-      #       echo -e "\n📁 Generando archivo .npmrc en: $npmrcPath"
-      #       cat <<EOF > "$npmrcPath"
-      #       //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
-      #       registry=$REPO_URL
-      #       EOF
-      #       ls -l $npmrcPath
-      #   displayName: "🔐 Setup CodeArtifact & npm config"
-      #   condition: succeeded()
-      #   env:
-      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
-      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
-      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
+            npmrcPath="$(file)/$(msName)/.npmrc"
+            echo -e "\n📁 Generando archivo .npmrc en: $npmrcPath"
+            cat <<EOF > "$npmrcPath"
+            //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
+            registry=$REPO_URL
+            EOF
+            ls -l $npmrcPath
+        displayName: "🔐 Setup CodeArtifact & npm config"
+        condition: succeeded()
+        env:
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
-      # - script: |
-      #     echo -e "\n📁 Archivo .env.local: app-administration-vue2"
-      #     printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
-      #     printenv | grep "^ADMIN_" | sed "s/^ADMIN_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
-      #     ls -l app-legacy/app-administration-vue2/.env.local
-      #     cat app-legacy/app-administration-vue2/.env.local
+      - script: |
+          echo -e "\n📁 Archivo .env.local: app-administration-vue2"
+          printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
+          printenv | grep "^ADMIN_" | sed "s/^ADMIN_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
+          ls -l app-legacy/app-administration-vue2/.env.local
+          cat app-legacy/app-administration-vue2/.env.local
 
-      #     echo -e "\n📁 Archivo .env.local: app-sellers-vue2"
-      #     printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
-      #     printenv | grep "^SELLERS_" | sed "s/^SELLERS_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
-      #     ls -l app-legacy/app-sellers-vue2/.env.local
-      #     cat app-legacy/app-sellers-vue2/.env.local
+          echo -e "\n📁 Archivo .env.local: app-sellers-vue2"
+          printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
+          printenv | grep "^SELLERS_" | sed "s/^SELLERS_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
+          ls -l app-legacy/app-sellers-vue2/.env.local
+          cat app-legacy/app-sellers-vue2/.env.local
 
-      #     echo -e "\n📁 Archivo .env: invictus"
-      #     printenv | grep -i "^INVICTUS_" |sed "s/^INVICTUS_//" > $(System.DefaultWorkingDirectory)/apps/invictus/.env
-      #     ls -l apps/invictus/.env
-      #     cat apps/invictus/.env
+          echo -e "\n📁 Archivo .env: invictus"
+          printenv | grep -i "^INVICTUS_" |sed "s/^INVICTUS_//" > $(System.DefaultWorkingDirectory)/apps/invictus/.env
+          ls -l apps/invictus/.env
+          cat apps/invictus/.env
 
-      #     echo -e "\n📁 Archivos .env para el path raiz"
-      #     printenv | grep "^ROOT_" | sed "s/^ROOT_//" > $(System.DefaultWorkingDirectory)/.env
-      #     ls -l .env
-      #     cat .env
-      #   displayName: "⚙️ Generate .env"
-      #   condition: succeeded()
+          echo -e "\n📁 Archivos .env para el path raiz"
+          printenv | grep "^ROOT_" | sed "s/^ROOT_//" > $(System.DefaultWorkingDirectory)/.env
+          ls -l .env
+          cat .env
+        displayName: "⚙️ Generate .env"
+        condition: succeeded()
 
-      # - script: |
-      #     echo -e "\n📁 Archivos .env: $(msName)"
-      #     printenv | grep -i "^$(msName)_" |sed -E "s/^($(msName))_//I" > $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
-      #     cat apps/invictus/.env >> $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
-      #     ls -l apps/$(msName)/.env
-      #     cat apps/$(msName)/.env
-      #   displayName: "⚙️ Generate $(msName) .env"
-      #   condition: and(succeeded(),
-      #     ne(variables['msName'], 'app-administration-vue2'),
-      #     ne(variables['msName'], 'app-sellers-vue2'))
+      - script: |
+          echo -e "\n📁 Archivos .env: $(msName)"
+          printenv | grep -i "^$(msName)_" |sed -E "s/^($(msName))_//I" > $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
+          cat apps/invictus/.env >> $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
+          ls -l apps/$(msName)/.env
+          cat apps/$(msName)/.env
+        displayName: "⚙️ Generate $(msName) .env"
+        condition: and(succeeded(),
+          ne(variables['msName'], 'app-administration-vue2'),
+          ne(variables['msName'], 'app-sellers-vue2'))
 
-      # - script: |
-      #     cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
-      #     echo "🔧 Actualizando versión en $(file)/$(msName)/package.json: $(msVersion)"
-      #     jq --arg version "$(msVersion)" '.version = $version' package.json > tmp.json && mv tmp.json package.json
+      - script: |
+          cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
+          echo "🔧 Actualizando versión en $(file)/$(msName)/package.json: $(msVersion)"
+          jq --arg version "$(msVersion)" '.version = $version' package.json > tmp.json && mv tmp.json package.json
 
-      #     echo -e "\n📁 File package.json:"      
-      #     cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/package.json
-      #   displayName: "📝 Update Version package.json"
-      #   condition: succeeded()
+          echo -e "\n📁 File package.json:"      
+          cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/package.json
+        displayName: "📝 Update Version package.json"
+        condition: succeeded()
 
-      # - task: NodeTool@0
-      #   displayName: "🔧 Install Nodejs $(nodeVersion)"
-      #   inputs:
-      #     versionSource: "spec"
-      #     versionSpec: "$(nodeVersion)"
-      #   condition: succeeded()
+      - task: NodeTool@0
+        displayName: "🔧 Install Nodejs $(nodeVersion)"
+        inputs:
+          versionSource: "spec"
+          versionSpec: "$(nodeVersion)"
+        condition: succeeded()
 
-      # - script: |
-      #     echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
-      #     cat <<EOF > "$(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
-      #     node-linker=hoisted
-      #     shamefully-hoist=true
-      #     ignore-scripts=false
-      #     allow-build-script=true
-      #     strict-peer-dependencies=false
-      #     EOF
-      #     ls -l $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
-      #     cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
+      - script: |
+          echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
+          cat <<EOF > "$(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
+          node-linker=hoisted
+          shamefully-hoist=true
+          ignore-scripts=false
+          allow-build-script=true
+          strict-peer-dependencies=false
+          EOF
+          ls -l $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
+          cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
 
-      #     # cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
-      #     cd $(System.DefaultWorkingDirectory)
-      #     echo -e "\n⚙️ Instalando dependencias node..."
-      #     npm install -g pnpm
-      #     pnpm install
-      #     # pnpm ignored-builds
+          # cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
+          cd $(System.DefaultWorkingDirectory)
+          echo -e "\n⚙️ Instalando dependencias node..."
+          npm install -g pnpm
+          pnpm install
+          # pnpm ignored-builds
 
-      #     OUTPUT=$(pnpm ls --depth=0 || true)
-      #     if [[ -z "$OUTPUT" ]]; then
-      #       echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
-      #       exit 99
-      #     else
-      #       echo -e "\n✅ Dependencias Instaladas:"
-      #       echo "$OUTPUT"
-      #     fi
-      #   displayName: "⚙️ Install Dependencies"
-      #   condition: succeeded()
+          OUTPUT=$(pnpm ls --depth=0 || true)
+          if [[ -z "$OUTPUT" ]]; then
+            echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
+            exit 99
+          else
+            echo -e "\n✅ Dependencias Instaladas:"
+            echo "$OUTPUT"
+          fi
+        displayName: "⚙️ Install Dependencies"
+        condition: succeeded()
 
-      # - script: |
-      #     echo -e "\n📦 Build MicroFrontend..."
+      - script: |
+          echo -e "\n📦 Build MicroFrontend..."
 
-      #     if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
-      #       cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
-      #       pnpm run build
-      #     else
-      #       pnpm run build --filter=...$(msName)
-      #     fi
+          if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
+            cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
+            pnpm run build
+          else
+            pnpm run build --filter=...$(msName)
+          fi
 
-      #     DIST_PATH="$(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist"
+          DIST_PATH="$(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist"
 
-      #     if [[ ! -d "$DIST_PATH" ]] || [[ -z "$(ls -A "$DIST_PATH" 2>/dev/null)" ]]; then
-      #       echo -e "\n##vso[task.logissue type=error]⚠️ Error: No se generó el build o la carpeta dist está vacía." 
-      #       exit 99
-      #     else
-      #       #################################DEPLOY MULTI AMBIENTE############################
-      #       CURRENT_BRANCH=$(echo $(Build.SourceBranch))
-      #       if [[ "$CURRENT_BRANCH" =~ ^refs/heads/(develop|staging)$ ]]; then
-      #         mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$environments"
-      #         cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$environments/$(msName)
-      #       else
-      #         mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$region"
-      #         cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$region/$(msName)
-      #       fi
+          if [[ ! -d "$DIST_PATH" ]] || [[ -z "$(ls -A "$DIST_PATH" 2>/dev/null)" ]]; then
+            echo -e "\n##vso[task.logissue type=error]⚠️ Error: No se generó el build o la carpeta dist está vacía." 
+            exit 99
+          else
+            #################################DEPLOY MULTI AMBIENTE############################
+            CURRENT_BRANCH=$(echo $(Build.SourceBranch))
+            if [[ "$CURRENT_BRANCH" =~ ^refs/heads/(develop|staging)$ ]]; then
+              mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$environments"
+              cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$environments/$(msName)
+            else
+              mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$region"
+              cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$region/$(msName)
+            fi
 
-      #       echo "✅ Build generado correctamente en $DIST_PATH"
-      #       ls -l "$DIST_PATH"
-      #     fi
-      #   displayName: "📦 Build $(msName)"
-      #   condition: succeeded()
-      #   env:
-      #     region: ${{ parameters.region }}
-      #     environments: ${{ parameters.environments }}
+            echo "✅ Build generado correctamente en $DIST_PATH"
+            ls -l "$DIST_PATH"
+          fi
+        displayName: "📦 Build $(msName)"
+        condition: succeeded()
+        env:
+          region: ${{ parameters.region }}
+          environments: ${{ parameters.environments }}
 
-      # - task: PublishBuildArtifacts@1
-      #   inputs:
-      #     PathtoPublish: "$(Build.ArtifactStagingDirectory)/dists"
-      #     ArtifactName: "dists"
-      #     publishLocation: "Container"
-      #   displayName: "📤 Publish Dist Files"
-      #   condition: and(succeeded(),
-      #     not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')),
-      #     not(startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
+      - task: PublishBuildArtifacts@1
+        inputs:
+          PathtoPublish: "$(Build.ArtifactStagingDirectory)/dists"
+          ArtifactName: "dists"
+          publishLocation: "Container"
+        displayName: "📤 Publish Dist Files"
+        condition: and(succeeded(),
+          not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')),
+          not(startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
