feat: refactor files

diff --git a/pipeline/ci/build/build-backend.yml b/pipeline/ci/build/build-backend.yml
--- a/pipeline/ci/build/build-backend.yml
+++ b/pipeline/ci/build/build-backend.yml
@@ -126,31 +126,19 @@ jobs:
         condition: succeeded()
 
       - script: |
-          # REPO_NAME="$(Build.Repository.Name)"
-          # branch="${BUILD_SOURCEBRANCH#refs/heads/}"
-          # environment="unknown"
-
-
-
           REPO_NAME="$(Build.Repository.Name)"
-          CURRENT_BRANCH="$BUILD_SOURCEBRANCH"
-
-          echo -e "\nℹ️ Informacion..."
-          echo "Branch: $CURRENT_BRANCH"
-          echo "Repositorio: $REPO_NAME"
-
-          CLEAN_NAME="${REPO_NAME%-invictus}"
-          branch="${CURRENT_BRANCH#refs/heads/}"
+          branch="${BUILD_SOURCEBRANCH#refs/heads/}"
+          environment="unknown"
 
           case "$branch" in
             develop)
-              clean_branch="$branch"
+              environment="develop"
               ;;
             staging)
-              clean_branch="qa"
+              environment="qa"
               ;;
             master)
-              clean_branch="prd"
+              environment="prd"
               ;;
           esac
 
@@ -159,12 +147,15 @@ jobs:
             exit 99
           fi
 
-          echo -e "\nℹ️ Informacion..."
-          echo "Clean Branch: $clean_branch"
-          echo "Clean Repositorio: $CLEAN_NAME"
+          cleanMsName=$(echo "$REPO_NAME" | sed -E 's/^microservice-//; s/-invictus$//')
+          ECR_REPOSITORY="${REPO_NAME%-invictus}"
+          ECR_REPOSITORY="$ECR_REPOSITORY-$environment"
 
-          echo "##vso[task.setvariable variable=clean_name_ecr]$CLEAN_NAME"
-          echo "##vso[task.setvariable variable=branch_docker]$clean_branch"
+          echo -e "\nℹ️ Repositorio $REPO_NAME..."
+          echo "MS Name: $cleanMsName"
+          echo "ECR Repositorio: $ECR_REPOSITORY"
+
+          echo "##vso[task.setvariable variable=ecr_repository]$ECR_REPOSITORY"
         displayName: "📛 Set ECR Repository Name"
         condition: succeeded()
 
@@ -174,7 +165,7 @@ jobs:
         inputs:
           command: "build"
           Dockerfile: "$(Build.Repository.Name)/Dockerfile"
-          repository: "$(ACCOUNT_ID_DEPLOY).dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com/$(clean_name_ecr)-$(branch_docker)"
+          repository: "$(ACCOUNT_ID_DEPLOY).dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com/$(ecr_repository)"
           tags: |
             latest
             $(version)
@@ -186,27 +177,25 @@ jobs:
       #       image \
       #       --severity CRITICAL,HIGH \
       #       --exit-code 1 \
-      #       $(ACCOUNT_ID_DEPLOY).dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com/$(clean_name_ecr)-$(branch_docker):$(version)
+      #       $(ACCOUNT_ID_DEPLOY).dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com/$(ecr_repository):$(version)
       #   displayName: "🛡️ Trivy scan Docker image"
       #   continueOnError: true
       #   condition: and(succeeded(),
       #     ne(variables['Build.SourceBranchName'], 'master'))
 
       - script: |
-          echo -e "\nℹ️ Verificando si existe el repositorio $(clean_name_ecr)-$(branch_docker)..."
+          echo -e "\nℹ️ Verificando repositorio $(ecr_repository)..."
           aws ecr describe-repositories \
-            --repository-names $(clean_name_ecr)-$(branch_docker) \
+            --repository-names $(ecr_repository) \
             --region $AWS_DEFAULT_REGION > /dev/null 2>&1
 
           if [ $? -ne 0 ]; then
-            echo "⚠️ Repositorio no existe. Creándolo..."
-            aws ecr create-repository \
-              --repository-name $(clean_name_ecr)-$(branch_docker) \
-              --region $AWS_DEFAULT_REGION
+            echo -e "\n##vso[task.logissue type=error]⚠️ Repositorio $(ecr_repository) no existe."
+            exit 99
           else
-            echo "✅ Repositorio ya existe. Continuando..."
+            echo "✅ Repositorio $(ecr_repository) existe"
           fi
-        displayName: "🛡️ Ensure ECR Repository Exists"
+        displayName: "🔍 Verify ECR Repository Exists"
         condition: succeeded()
         env:
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
@@ -214,11 +203,11 @@ jobs:
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
       - task: Docker@2
-        displayName: "🚀 Push Docker Image $(Build.SourceBranchName) -> $(Build.Repository.Name)"
+        displayName: "🚀 Push Docker Image $(Build.Repository.Name)"
         condition: succeeded()
         inputs:
           command: "Push"
-          repository: "$(ACCOUNT_ID_DEPLOY).dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com/$(clean_name_ecr)-$(branch_docker)"
+          repository: "$(ACCOUNT_ID_DEPLOY).dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com/$(ecr_repository)"
           tags: |
             latest
             $(version)
