Update files

diff --git a/pipeline/ci/test/test-backend.yml b/pipeline/ci/test/test-backend.yml
--- a/pipeline/ci/test/test-backend.yml
+++ b/pipeline/ci/test/test-backend.yml
@@ -13,12 +13,13 @@ jobs:
       - task: DownloadBuildArtifacts@0
         inputs:
           artifactName: "versions"
-          downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
+          downloadPath: "$(Pipeline.Workspace)/version-downloaded"
         displayName: "📥 Download Version Artifact"
+        condition: succeeded()
 
       - script: |
-          ls -R $(Pipeline.Workspace)/downloaded-versions/versions
-          VERSION_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/version.json"
+          ls -R $(Pipeline.Workspace)/version-downloaded/versions
+          VERSION_FILE="$(Pipeline.Workspace)/version-downloaded/versions/version.json"
           if [[ -f "$VERSION_FILE" ]]; then
             VERSION=$(jq -r '.version' $VERSION_FILE)            
             echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
@@ -28,23 +29,7 @@ jobs:
             exit 99
           fi
         displayName: "📖 Read Microservice Versions"
-
-      - task: NodeTool@0
-        displayName: "🔧 Install Nodejs $(nodeVersion)"
-        inputs:
-          versionSource: "spec"
-          versionSpec: "$(nodeVersion)"
-
-      - task: JavaToolInstaller@0
-        displayName: "🔧 Install JDK 17"
-        inputs:
-          versionSpec: "17"
-          jdkArchitectureOption: "x64"
-          jdkSourceOption: "PreInstalled"
-
-      - script: |
-          npm install -g pnpm
-        displayName: "⚙️ Install pnpm"
+        condition: succeeded()
 
       - task: Bash@3
         name: AuthCodeArtifact
@@ -70,7 +55,6 @@ jobs:
             echo "Verificando identidad de AWS..."
             aws sts get-caller-identity
 
-
             echo "Generando archivo .npmrc"
             cat <<EOF > ".npmrc"
             //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
@@ -78,23 +62,71 @@ jobs:
             EOF
             ls -la .npmrc
         displayName: "🔐 Setup CodeArtifact & npm config"
+        condition: succeeded()
         env:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
 
+      - task: NodeTool@0
+        inputs:
+          versionSource: "spec"
+          versionSpec: "$(nodeVersion)"
+        displayName: "🔧 Install Nodejs $(nodeVersion)"
+        condition: succeeded()
+
+      - script: |
+          echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/.pnpmrc"
+          cat <<EOF > "$(System.DefaultWorkingDirectory)/.pnpmrc"
+          node-linker=hoisted
+          shamefully-hoist=true
+          ignore-scripts=false
+          allow-build-script=true
+          strict-peer-dependencies=false
+          EOF
+          ls -l $(System.DefaultWorkingDirectory)/.pnpmrc
+          cat $(System.DefaultWorkingDirectory)/.pnpmrc
+
+          cat $(System.DefaultWorkingDirectory)/.pnpmrc >> $(System.DefaultWorkingDirectory)/.npmrc
+          echo -e "\n✅ Contenido de .pnpmrc anexado a .npmrc correctamente."
+
+          echo -e "\n⚙️ Instalando dependencias node..."
+          npm install -g pnpm
+          pnpm install
+          pnpm ignored-builds
+          
+          OUTPUT=$(pnpm ls --depth=0 || true)
+          if [[ -z "$OUTPUT" ]]; then
+            echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
+            exit 99
+          else
+            echo -e "\n✅ Dependencias Instaladas:"
+            echo "$OUTPUT"
+          fi
+        displayName: "⚙️ Install Dependencies"
+        condition: succeeded()
+
+      - task: JavaToolInstaller@0
+        inputs:
+          versionSpec: "17"
+          jdkArchitectureOption: "x64"
+          jdkSourceOption: "PreInstalled"
+        displayName: "🔧 Install JDK 17"
+        condition: succeeded()
+
       - task: SonarQubePrepare@7
-        displayName: "⚙️ Prepare SonarQube Analysis"
         inputs:
           SonarQube: "SonarQubeConection"
           scannerMode: "CLI"
           configMode: "manual"
-          cliProjectKey: "pruebas-$(Build.Repository.Name)"
-          cliProjectName: "pruebas-$(Build.Repository.Name)"
+          cliProjectKey: "$(Build.Repository.Name)"
+          cliProjectName: "$(Build.Repository.Name)"
           cliSources: "$(System.DefaultWorkingDirectory)"
           extraProperties: |
             sonar.javascript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/coverage/lcov.info
             sonar.exclusions=**/*.java,**/test/**,**/android/**,**/ios/**,**/coverage/**,**/.nyc_output/**,**/reports/**,**/node_modules/**,**/migrations/**,**/config/**
+        displayName: "⚙️ Prepare SonarQube Analysis"
+        condition: succeeded()
 
       - script: |
           response=$(echo $SONARQUBE_SCANNER_PARAMS | sed -E 's#"sonar\.branch\.name":"[^"]+",##g')
@@ -115,59 +147,33 @@ jobs:
       - script: |
           echo "🔧 Actualizando versión en package.json a $(msVersion)"
           jq --arg version "$(msVersion)" '.version = $version' package.json > tmp.json && mv tmp.json package.json
-        displayName: "🧪 Temporary version for build"
-
-      - script: |
-          pnpm install --ignore-scripts
-
-          OUTPUT=$(pnpm ls --depth=0 || true)
-          if [[ -z "$OUTPUT" ]]; then
-            echo "##vso[task.logissue type=error]❌ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
-            exit 99
-          else
-            echo "✅ Dependencias Instaladas:"
-            echo "$OUTPUT"
-          fi
-        displayName: "📦 Install Microservice Dependencies"
+        displayName: "⚙️ Temporary version for build"
+        condition: succeeded()
 
       - script: |
           pnpm run test
-        displayName: "🚀 Running Tests on $(Build.Repository.Name)"
+        displayName: "🧪 Run Tests for: $(Build.Repository.Name)"
+        condition: succeeded()
         continueOnError: true
 
       - script: |
           pnpm run coverage
+          ls -la $(System.DefaultWorkingDirectory)/coverage
         displayName: "🔎 Coverage Analysis: $(Build.Repository.Name)"
+        condition: succeeded()
         continueOnError: true
 
       - task: SonarQubeAnalyze@7
         displayName: "📡 Run Sonar Analysis"
+        condition: succeeded()
 
       - task: SonarQubePublish@7
-        displayName: "📤 Publish Static Code Analysis Results"
         inputs:
           pollingTimeoutSec: 400
+        displayName: "📤 Publish Static Code Analysis Results"
+        condition: succeeded()
 
-      - script: |
-          echo "Esperando Quality Gate..."
-
-          status=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=pruebas-$(Build.Repository.Name)")
-          metrics_response=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/measures/component?component=pruebas-$(Build.Repository.Name)&metricKeys=coverage,duplicated_lines_density")
-
-          coverage=$(echo "$metrics_response" | jq -r '.component.measures[] | select(.metric=="coverage") | .value')
-          duplication=$(echo "$metrics_response" | jq -r '.component.measures[] | select(.metric=="duplicated_lines_density") | .value')
-
-          status_code=$(echo "$status" | jq -r '.projectStatus.status')
-          echo "🔹 Proyecto: pruebas-$(Build.Repository.Name) | Coverage: $coverage | Lines Duplications: $duplication | Estado: $status_code"
-
-          if [[ "$status_code" == "ERROR" ]]; then
-            echo "##vso[task.logissue type=error]❌ El proyecto fallo su Quality Gate."
-            exit 99
-          else
-            echo "✅ El proyecto pasó su Quality Gate."
-          fi
-        env:
-          SONAR_TOKEN: $(SONAR_TOKEN)
-          SONAR_HOST_URL: $(SONAR_HOST_URL)
-        displayName: "🛡️ Quality Gate Check: $(Build.Repository.Name)"
-        continueOnError: true
+      - template: sonarqube/job-sonarqube.yml@sonarqube
+        condition: succeeded()
+        parameters:
+          projectKey: $(Build.Repository.Name)
