feat: validar console logs y tests en el repo

diff --git a/pipeline/ci/general/semantic-version-backend.yml b/pipeline/ci/general/semantic-version-backend.yml
--- a/pipeline/ci/general/semantic-version-backend.yml
+++ b/pipeline/ci/general/semantic-version-backend.yml
@@ -104,7 +104,7 @@ jobs:
 
             git fetch origin "$targetBranch"
             diff=$(git --no-pager diff "origin/$targetBranch..origin/$sourceBranch")
-            pattern='console[.]'
+            pattern='console[.](log|error|warn|info|debug)'
 
             console_logs=$(echo "$diff" | awk -v pat="$pattern" '
               /^\+\+\+ b\// {
@@ -127,7 +127,7 @@ jobs:
               /^ / { line++ }
             ')
 
-            if echo "$diff" | grep -qE '^\+.*console\.'; then
+            if echo "$diff" | grep -qE "^\+.*$pattern"; then
               echo -e "$\n🧨 Archivos detectados con console.* en el código 🧨"
               echo "$console_logs"
               echo -e "\n##vso[task.logissue type=error]⚠️ Se encontro 'console.*' en los cambios"
@@ -136,6 +136,62 @@ jobs:
               echo -e "\n✅ No se encontraron sentencias 'console.*' en los cambios"
             fi
         displayName: "🔎 Validate for 'console.*' in changes"
+        condition: and(succeeded(), or(
+          eq(variables['Build.Reason'], 'PullRequest'),
+          startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
+          startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
+
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            if [[ "$(Build.Reason)" == "PullRequest" ]]; then
+              sourceBranch="$(System.PullRequest.SourceBranch)"
+              sourceBranch="${sourceBranch/refs\/heads\//}"
+            else
+              sourceBranch="${BUILD_SOURCEBRANCH/refs\/heads\//}"
+            fi
+
+            echo -e "\n🔎 Verificando que no se hayan agregado nuevas sentencias describe.* ..."
+            targetBranch="master"
+            echo "Branch actual: $sourceBranch"
+            echo "Branch destino: $targetBranch"
+
+            git fetch origin "$targetBranch"
+            diff=$(git --no-pager diff "origin/$targetBranch..origin/$sourceBranch")
+            pattern='((describe|it|test|suite|specify)[.]only|fdescribe|fit|ftest)'
+
+            describe_tests=$(echo "$diff" | awk -v pat="$pattern" '
+              /^\+\+\+ b\// {
+                file=$0
+                sub(/^\+\+\+ b\//,"",file)
+              }
+              /^@@/ {
+                if (match($0, /\+([0-9]+)/, arr)) {
+                  line=arr[1]
+                } else {
+                  line=0
+                }
+              }
+              /^\+/ && !/^\+\+\+/ {
+                if ($0 ~ pat) {
+                  print file ":" line ":" substr($0, 2)
+                }
+                line++
+              }
+              /^ / { line++ }
+            ')
+
+            if echo "$diff" | grep -qE "^\+.*$pattern"; then
+              echo -e "\n🧨 Archivos detectados con describe.* en el código 🧨"
+              echo "$describe_tests"
+              echo -e "\n##vso[task.logissue type=error]⚠️ Se detectaron 'describe.*' en los cambios"
+              exit 99
+            else
+              echo -e "\n✅ No se encontraron sentencias 'describe.*' en los cambios"
+            fi
+        displayName: "🔎 Validate 'describe.*' in changes"
         condition: and(succeeded(), or(
           eq(variables['Build.Reason'], 'PullRequest'),
           startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
