Updates

diff --git a/pipeline/ci/general/semantic-version-backend.yml b/pipeline/ci/general/semantic-version-backend.yml
--- a/pipeline/ci/general/semantic-version-backend.yml
+++ b/pipeline/ci/general/semantic-version-backend.yml
@@ -48,56 +48,56 @@ jobs:
           startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
           startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
 
-      # - script: |
-      #     sourceBranch="${BUILD_SOURCEBRANCH/refs\/heads\//}"
-      #     targetBranch="master"
+      - script: |
+          sourceBranch="${BUILD_SOURCEBRANCH/refs\/heads\//}"
+          targetBranch="master"
 
-      #     echo -e "\n🔎 Verificando que no se hayan agregado nuevas sentencias console.log..."
-      #     echo "Branch actual: $sourceBranch"
-      #     echo "Branch destino: $targetBranch"
+          echo -e "\n🔎 Verificando que no se hayan agregado nuevas sentencias console.log..."
+          echo "Branch actual: $sourceBranch"
+          echo "Branch destino: $targetBranch"
 
-      #     git fetch origin "$targetBranch"
-      #     diff=$(git --no-pager diff "origin/$targetBranch..origin/$sourceBranch")
+          git fetch origin "$targetBranch"
+          diff=$(git --no-pager diff "origin/$targetBranch..origin/$sourceBranch")
 
-      #     console_logs=$(echo "$diff" | awk '
-      #       # Captura el archivo actual
-      #       /^\+\+\+ b\// {
-      #         file=$0
-      #         sub(/^\+\+\+ b\//,"",file)
-      #       }
+          console_logs=$(echo "$diff" | awk '
+            # Captura el archivo actual
+            /^\+\+\+ b\// {
+              file=$0
+              sub(/^\+\+\+ b\//,"",file)
+            }
 
-      #       # Captura el inicio del hunk: @@ -a,b +c,d @@
-      #       /^@@/ {
-      #         match($0, /\+([0-9]+)/, arr)
-      #         line=arr[1]
-      #       }
+            # Captura el inicio del hunk: @@ -a,b +c,d @@
+            /^@@/ {
+              match($0, /\+([0-9]+)/, arr)
+              line=arr[1]
+            }
 
-      #       # Línea agregada
-      #       /^\+/ && !/^\+\+\+/ {
-      #         if ($0 ~ /console\.log/) {
-      #           print file ":" line ":" substr($0, 2)
-      #         }
-      #         line++
-      #       }
+            # Línea agregada
+            /^\+/ && !/^\+\+\+/ {
+              if ($0 ~ /console\.log/) {
+                print file ":" line ":" substr($0, 2)
+              }
+              line++
+            }
 
-      #       # Línea de contexto
-      #       /^ / {
-      #         line++
-      #       }
-      #     ')
+            # Línea de contexto
+            /^ / {
+              line++
+            }
+          ')
 
-      #     if echo "$diff" | grep -qE '^\+.*console\.log'; then
-      #       echo -e "$\n🧨 Archivos detectados con console.log en el código 🧨"
-      #       echo "$console_logs"
-      #       echo -e "\n##vso[task.logissue type=error]⚠️ Se encontro 'console.log' en los cambios"
-      #       exit 99
-      #     else
-      #       echo -e "\n✅ No se encontraron sentencias 'console.log' en los cambios"
-      #     fi
-      #   displayName: "🔍 Validate for 'console.log' in changes"
-      #   condition: and(succeeded(), or(
-      #     startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
-      #     startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
+          if echo "$diff" | grep -qE '^\+.*console\.log'; then
+            echo -e "$\n🧨 Archivos detectados con console.log en el código 🧨"
+            echo "$console_logs"
+            echo -e "\n##vso[task.logissue type=error]⚠️ Se encontro 'console.log' en los cambios"
+            exit 99
+          else
+            echo -e "\n✅ No se encontraron sentencias 'console.log' en los cambios"
+          fi
+        displayName: "🔍 Validate for 'console.log' in changes"
+        condition: and(succeeded(), or(
+          startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
+          startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
 
       - script: |
           REPO_NAME="$(Build.Repository.Name)"          
