feat: added validation branch name

diff --git a/pipeline/ci/general/semantic-version-frontend.yml b/pipeline/ci/general/semantic-version-frontend.yml
--- a/pipeline/ci/general/semantic-version-frontend.yml
+++ b/pipeline/ci/general/semantic-version-frontend.yml
@@ -42,6 +42,23 @@ jobs:
           targetType: inline
           script: |
             set -e
+            echo -e "\nℹ️ Validando branch: $(Build.SourceBranchName)"
+            REGEX='^(feature\/[a-zA-Z0-9._-]+|hotfix\/[a-zA-Z0-9._-]+|develop|staging|master)$'
+            if [[ ! "$(Build.SourceBranchName)" =~ $REGEX ]]; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ Error: la rama '$(Build.SourceBranchName)' no cumple con el nombramiento."
+              echo "##vso[task.logissue type=error] Usa: feature/*, hotfix/*, develop, staging o master"
+              exit 99
+            else
+            echo "✅ Nombre de la rama es valido"
+            fi
+        displayName: "🔎 Validate Branch Name"
+        condition: succeeded()
+
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
             echo -e "\n📌 Verificando si feature está actualizada con master y si hay cambios relevantes..."
             echo "Branch Actual: $(echo $(Build.SourceBranch))"          
             git fetch origin master
