feat: update file

diff --git a/pipeline/ci/general/semantic-version-electron.yml b/pipeline/ci/general/semantic-version-electron.yml
--- a/pipeline/ci/general/semantic-version-electron.yml
+++ b/pipeline/ci/general/semantic-version-electron.yml
@@ -71,55 +71,55 @@ jobs:
           startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
           startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
 
-      # - task: Bash@3
-      #   inputs:
-      #     targetType: inline
-      #     script: |
-      #       set -e
-      #       sourceBranch="${BUILD_SOURCEBRANCH/refs\/heads\//}"
-      #       targetBranch="master"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            sourceBranch="${BUILD_SOURCEBRANCH/refs\/heads\//}"
+            targetBranch="master"
 
-      #       echo -e "\n🔎 Verificando que no se hayan agregado nuevas sentencias console.* ..."
-      #       echo "Branch actual: $sourceBranch"
-      #       echo "Branch destino: $targetBranch"
+            echo -e "\n🔎 Verificando que no se hayan agregado nuevas sentencias console.* ..."
+            echo "Branch actual: $sourceBranch"
+            echo "Branch destino: $targetBranch"
 
-      #       git fetch origin "$targetBranch"
-      #       diff=$(git --no-pager diff "origin/$targetBranch..origin/$sourceBranch")
-      #       pattern='console[.]'
+            git fetch origin "$targetBranch"
+            diff=$(git --no-pager diff "origin/$targetBranch..origin/$sourceBranch")
+            pattern='console[.]'
 
-      #       console_logs=$(echo "$diff" | awk -v pat="$pattern" '
-      #         /^\+\+\+ b\// {
-      #           file=$0
-      #           sub(/^\+\+\+ b\//,"",file)
-      #         }
-      #         /^@@/ {
-      #           if (match($0, /\+([0-9]+)/, arr)) {
-      #             line=arr[1]
-      #           } else {
-      #             line=0
-      #           }
-      #         }
-      #         /^\+/ && !/^\+\+\+/ {
-      #           if ($0 ~ pat) {
-      #             print file ":" line ":" substr($0, 2)
-      #           }
-      #           line++
-      #         }
-      #         /^ / { line++ }
-      #       ')
+            console_logs=$(echo "$diff" | awk -v pat="$pattern" '
+              /^\+\+\+ b\// {
+                file=$0
+                sub(/^\+\+\+ b\//,"",file)
+              }
+              /^@@/ {
+                if (match($0, /\+([0-9]+)/, arr)) {
+                  line=arr[1]
+                } else {
+                  line=0
+                }
+              }
+              /^\+/ && !/^\+\+\+/ {
+                if ($0 ~ pat) {
+                  print file ":" line ":" substr($0, 2)
+                }
+                line++
+              }
+              /^ / { line++ }
+            ')
 
-      #       if echo "$diff" | grep -qE '^\+.*console\.'; then
-      #         echo -e "\n🧨 Archivos detectados con console.* en el código 🧨"
-      #         echo "$console_logs"
-      #         echo -e "\n##vso[task.logissue type=error]⚠️ Se encontro 'console.*' en los cambios"
-      #         exit 99
-      #       else
-      #         echo -e "\n✅ No se encontraron sentencias 'console.*' en los cambios"
-      #       fi
-      #   displayName: "🔎 Validate for 'console.*' in changes"
-      #   condition: and(succeeded(), or(
-      #     startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
-      #     startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
+            if echo "$diff" | grep -qE '^\+.*console\.'; then
+              echo -e "\n🧨 Archivos detectados con console.* en el código 🧨"
+              echo "$console_logs"
+              echo -e "\n##vso[task.logissue type=error]⚠️ Se encontro 'console.*' en los cambios"
+              exit 99
+            else
+              echo -e "\n✅ No se encontraron sentencias 'console.*' en los cambios"
+            fi
+        displayName: "🔎 Validate for 'console.*' in changes"
+        condition: and(succeeded(), or(
+          startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
+          startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
 
       - task: Bash@3
         inputs:
