Update files

diff --git a/pipeline/general/semantic-version-frontend.yml b/pipeline/general/semantic-version-frontend.yml
--- a/pipeline/general/semantic-version-frontend.yml
+++ b/pipeline/general/semantic-version-frontend.yml
@@ -31,7 +31,7 @@ jobs:
         displayName: "📂 Select File"
 
       - script: |
-          echo "📌 Verificando si feature está actualizada con master y si hay cambios relevantes..."
+          echo -e "\n📌 Verificando si feature está actualizada con master y si hay cambios relevantes..."
 
           git fetch origin master
 
@@ -40,9 +40,9 @@ jobs:
 
           # Verifica si la rama está actualizada
           if [ "$MERGE_BASE" = "$(git rev-parse origin/master)" ]; then
-            echo "✅ La rama feature está actualizada con master."
+            echo -e "\n✅ La rama feature está actualizada con master."
           else
-            echo "⚠️ La rama feature NO contiene todos los commits de master. Verificando cambios relevantes en master..."
+            echo -e "\n⚠️ La rama feature NO contiene todos los commits de master. Verificando cambios relevantes en master..."
 
             # Obtén los archivos cambiados en master desde el punto de bifurcación
             CHANGED_FILES=$(git diff --name-only "$MERGE_BASE".."origin/master")
@@ -54,10 +54,10 @@ jobs:
             RELEVANT_CHANGES=$(echo "$CHANGED_FILES" | grep -vE '^pipeline/')
 
             if [[ -z "$RELEVANT_CHANGES" ]]; then
-              echo "ℹ️ Solo hay cambios en archivos ignorados (pipeline/). Continuando..."
+              echo -e "\nℹ️ Solo hay cambios en archivos ignorados (pipeline/). Continuando..."
             else
-              echo "##vso[task.logissue type=error]❌ Cambios relevantes detectados en master y no están integrados. Debes actualizar tu rama."
-              exit 1
+              echo -e "\n##vso[task.logissue type=error]❌ Cambios relevantes detectados en master y no están integrados. Debes actualizar tu rama."
+              exit 99
             fi
           fi
         displayName: "🔎 Validate Feature or Hotfix Branch is Up to Date"
