feat: refactor tasks

diff --git a/pipeline/cd/deploy/deploy-electron.yml b/pipeline/cd/deploy/deploy-electron.yml
--- a/pipeline/cd/deploy/deploy-electron.yml
+++ b/pipeline/cd/deploy/deploy-electron.yml
@@ -26,51 +26,66 @@ jobs:
         displayName: "📥 Download Version"
         condition: succeeded()
 
-      - script: |
-          VERSION_FILE="$(Pipeline.Workspace)/versions/electron/version.json"
-          if [[ -f "$VERSION_FILE" ]]; then
-            VERSION=$(jq -r '.version' $VERSION_FILE)
-            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
-            echo "##vso[task.setvariable variable=version]$VERSION"
-          else
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
-            exit 99
-          fi
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            VERSION_FILE="$(Pipeline.Workspace)/versions/electron/version.json"
+            echo -e "\n📁 Archivo version.json:"
+            ls -la "$VERSION_FILE"
+            cat "$VERSION_FILE"
+
+            if [[ -f "$VERSION_FILE" ]]; then
+              VERSION=$(jq -r '.version' $VERSION_FILE)
+              echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
+              echo "##vso[task.setvariable variable=version]$VERSION"
+            else
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
+              exit 99
+            fi
         displayName: "📚 Read Version"
         condition: succeeded()
 
-      - script: |
-          CURRENT_BRANCH="$(Build.SourceBranchName)"
-          environment="develop"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            CURRENT_BRANCH="$(Build.SourceBranchName)"
+            environment="develop"
 
-          case "$CURRENT_BRANCH" in 
-            staging) environment="$environment_staging" ;;
-            master) environment="$region" ;;
-          esac
+            case "$CURRENT_BRANCH" in 
+              staging) environment="$environment_staging" ;;
+              master) environment="$region" ;;
+            esac
 
-          echo "##vso[task.setvariable variable=environment]$environment"
-          echo -e "\n✅ Environment asignado exitosamente"
-          echo "Environment: $environment"
+            echo "##vso[task.setvariable variable=environment]$environment"
+            echo -e "\n✅ Environment asignado exitosamente"
+            echo "Environment: $environment"
         displayName: "⚙️ Generate .env"
         condition: succeeded()
         env:
           region: ${{ parameters.region }}
           environment_staging: ${{ parameters.environment_staging }}
 
-      - script: |
-          set -e
-          echo -e "\n📦 Cargando al Bucket S3..."
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📦 Cargando al Bucket S3..."
 
-          BASE_PATH="$(Pipeline.Workspace)/release/$(environment)/linux"
-          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
-          ls -l "$BASE_PATH"
-          echo ""
+            BASE_PATH="$(Pipeline.Workspace)/release/$(environment)/linux"
+            echo -e "\n📂 Archivos a cargar: $BASE_PATH"
+            ls -l "$BASE_PATH"
+            echo ""
 
-          aws s3 cp "$BASE_PATH" "s3://download-$(ACCOUNT_ID_INVICTUS)/app/linux/" --recursive
+            aws s3 cp "$BASE_PATH" "s3://download-$(ACCOUNT_ID_INVICTUS)/app/linux/" --recursive
 
-          echo -e "\n✅ Archivos subidos exitosamente."
-          echo "🔗 APP: InvictusUX-$(version).AppImage"
-          echo -e "\n##[command]🌐 URL: $(URL_APP)/app/linux/InvictusUX-$(version).AppImage"
+            echo -e "\n✅ Archivos subidos exitosamente."
+            echo "🔗 APP: InvictusUX-$(version).AppImage"
+            echo -e "\n##[command]🌐 URL: $(URL_APP)/app/linux/InvictusUX-$(version).AppImage"
         displayName: "🐧 Upload Bucket S3 Linux"
         condition: succeeded()
         env:
@@ -78,20 +93,23 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
 
-      - script: |
-          set -e
-          echo -e "\n📦 Cargando al Bucket S3..."
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📦 Cargando al Bucket S3..."
 
-          BASE_PATH="$(Pipeline.Workspace)/release/$(environment)/windows"
-          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
-          ls -l "$BASE_PATH"
-          echo ""
+            BASE_PATH="$(Pipeline.Workspace)/release/$(environment)/windows"
+            echo -e "\n📂 Archivos a cargar: $BASE_PATH"
+            ls -l "$BASE_PATH"
+            echo ""
 
-          aws s3 cp "$BASE_PATH" "s3://download-$(ACCOUNT_ID_INVICTUS)/app/windows/" --recursive
+            aws s3 cp "$BASE_PATH" "s3://download-$(ACCOUNT_ID_INVICTUS)/app/windows/" --recursive
 
-          echo -e "\n✅ Archivos subidos exitosamente."
-          echo "🔗 APP: InvictusUX Setup $(version).exe"
-          echo -e "\n##[command]🌐 URL: $(URL_APP)/app/windows/InvictusUX%20Setup%20$(version).exe"
+            echo -e "\n✅ Archivos subidos exitosamente."
+            echo "🔗 APP: InvictusUX Setup $(version).exe"
+            echo -e "\n##[command]🌐 URL: $(URL_APP)/app/windows/InvictusUX%20Setup%20$(version).exe"
         displayName: "🖥️ Upload Bucket S3 Windows"
         condition: succeeded()
         env:
@@ -99,24 +117,27 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
 
-      - script: |
-          set -e
-          echo -e "\nℹ️ Enviando Mensaje a SQS..."
-          echo "Cuenta : $(ACCOUNT_ID_INVICTUS)"
-          echo "Version: $(version)"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\nℹ️ Enviando Mensaje a SQS..."
+            echo "Cuenta : $(ACCOUNT_ID_INVICTUS)"
+            echo "Version: $(version)"
 
-          aws sqs send-message \
-            --queue-url https://sqs.us-east-1.amazonaws.com/$(ACCOUNT_ID_INVICTUS)/DynamicStorage \
-            --message-body '{
-              "model": {
-                "parameterName": "VERSION",
-                "parameterDescription": "Parámetro que indica la versión actual del sistema.",
-                "parameterOrigin": "GLOBAL_PARAMETER",
-                "parameterValue": "$(version)"
-              },
-              "event": "setParameter"
-            }' \
-            --delay-seconds 0
+            aws sqs send-message \
+              --queue-url https://sqs.us-east-1.amazonaws.com/$(ACCOUNT_ID_INVICTUS)/DynamicStorage \
+              --message-body '{
+                "model": {
+                  "parameterName": "VERSION",
+                  "parameterDescription": "Parámetro que indica la versión actual del sistema.",
+                  "parameterOrigin": "GLOBAL_PARAMETER",
+                  "parameterValue": "$(version)"
+                },
+                "event": "setParameter"
+              }' \
+              --delay-seconds 0
         displayName: "📩 Send Message SQS"
         condition: succeeded()
         env:
@@ -124,42 +145,46 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
 
-      - script: |
-          DEPLOY_TIME=$(date -d "$BUILD_FINISHTIME -5 hours" "+%Y-%m-%d %I:%M %p")
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            DEPLOY_TIME=$(date -d "$BUILD_FINISHTIME -5 hours" "+%Y-%m-%d %I:%M %p")
 
-          echo -e "\n📢 Generando notificación para Teams..."
-          echo "Pipeline   : $(Build.DefinitionName)"
-          echo "Branch     : $(environment)"
-          echo "Build      : $(Build.BuildNumber)"
-          echo "User       : $(Build.RequestedFor)"
-          echo "DeployTime : $DEPLOY_TIME"
-          echo ""
+            echo -e "\n📢 Generando notificación para Teams..."
+            echo "Pipeline   : $(Build.DefinitionName)"
+            echo "Branch     : $(environment)"
+            echo "Build      : $(Build.BuildNumber)"
+            echo "User       : $(Build.RequestedFor)"
+            echo "DeployTime : $DEPLOY_TIME"
+            echo ""
 
-          payload=$(cat <<EOF
-          {
-            "@type": "MessageCard",
-            "@context": "http://schema.org/extensions",
-            "summary": "Deployment successful",
-            "themeColor": "00FF00",
-            "title": "✅ Deployment exitoso $(Build.SourceBranchName)",
-            "sections": [
-              {
-                "facts": [
-                  { "name": "Pipeline", "value": "$(Build.DefinitionName)" },
-                  { "name": "Branch", "value": "$(environment)" },
-                  { "name": "Build", "value": "$(Build.BuildNumber)" },
-                  { "name": "Merged by", "value": "$(Build.RequestedFor)" },
-                  { "name": "Deploy time", "value": "$DEPLOY_TIME" }
-                ],
-                "markdown": true
-              }
-            ]
-          }
-          EOF
-          )
+            payload=$(cat <<EOF
+            {
+              "@type": "MessageCard",
+              "@context": "http://schema.org/extensions",
+              "summary": "Deployment successful",
+              "themeColor": "00FF00",
+              "title": "✅ Deployment exitoso $(Build.SourceBranchName)",
+              "sections": [
+                {
+                  "facts": [
+                    { "name": "Pipeline", "value": "$(Build.DefinitionName)" },
+                    { "name": "Branch", "value": "$(environment)" },
+                    { "name": "Build", "value": "$(Build.BuildNumber)" },
+                    { "name": "Merged by", "value": "$(Build.RequestedFor)" },
+                    { "name": "Deploy time", "value": "$DEPLOY_TIME" }
+                  ],
+                  "markdown": true
+                }
+              ]
+            }
+            EOF
+            )
 
-          curl -H "Content-Type: application/json" \
-               -d "$payload" \
-               $(URL_WEBHOOK_TEAMS)
+            curl -H "Content-Type: application/json" \
+                -d "$payload" \
+                $(URL_WEBHOOK_TEAMS)
         displayName: "📢 Post message to Teams"
         condition: succeeded()
diff --git a/pipeline/cd/deploy/deploy-flutter.yml b/pipeline/cd/deploy/deploy-flutter.yml
--- a/pipeline/cd/deploy/deploy-flutter.yml
+++ b/pipeline/cd/deploy/deploy-flutter.yml
@@ -26,91 +26,101 @@ jobs:
         displayName: "📥 Download Version"
         condition: succeeded()
 
-      - script: |
-          VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/flutter/version.json"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/flutter/version.json"
+            echo -e "\n📁 Archivo version.json:"
+            ls -la "$VERSION_FILE"
+            cat "$VERSION_FILE"
 
-          echo -e "\n📁 Archivo version.json:"
-          ls -la "$VERSION_FILE"
-          cat "$VERSION_FILE"
-
-          if [[ -f "$VERSION_FILE" ]]; then
-            VERSION=$(jq -r '.version' $VERSION_FILE)
-            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
-            echo "##vso[task.setvariable variable=version]$VERSION"
-          else
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
-            exit 99
-          fi
+            if [[ -f "$VERSION_FILE" ]]; then
+              VERSION=$(jq -r '.version' $VERSION_FILE)
+              echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
+              echo "##vso[task.setvariable variable=version]$VERSION"
+            else
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
+              exit 99
+            fi
         displayName: "📚 Read Version"
         condition: succeeded()
 
-      - script: |
-          CURRENT_BRANCH="$(Build.SourceBranch)"
-          environment="unknown"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            CURRENT_BRANCH="$(Build.SourceBranch)"
+            environment="unknown"
 
-          case "$CURRENT_BRANCH" in
-            refs/heads/feature/*) environment="dev"; ;;
-            refs/heads/develop)
-              if [[ "$environments" == "develop_new" ]]; then
-                environment="dev_new"
-              else
-                environment="dev"
-              fi
-              ;;
-            refs/heads/staging)
-              if [[ "$environments" == "staging_new" ]]; then
-                environment="qa_new"
-              elif [[ "$environments" == "staging_nacional" ]]; then
-                environment="qa_nacional"
-              else
-                environment="qa"
-              fi
-              ;;
-            refs/heads/master) 
-              case "$region" in
-                "antioquia") environment="prd-gana"; ;;
-                "cap")       environment="prd-cap"; ;;
-                "tolima")    environment="prd-seapto"; ;;
-                "huila")     environment="prd-suchance"; ;;
-                "cauca")     environment="prd-acertemos"; ;;
-                "boyaca")    environment="prd-jer"; ;;
-                "santander") environment="prd-laperla"; ;;
-                "putumayo")  environment="prd-matrixredes"; ;;
-              esac ;;
-          esac
+            case "$CURRENT_BRANCH" in
+              refs/heads/feature/*) environment="dev"; ;;
+              refs/heads/develop)
+                if [[ "$environments" == "develop_new" ]]; then
+                  environment="dev_new"
+                else
+                  environment="dev"
+                fi
+                ;;
+              refs/heads/staging)
+                if [[ "$environments" == "staging_new" ]]; then
+                  environment="qa_new"
+                elif [[ "$environments" == "staging_nacional" ]]; then
+                  environment="qa_nacional"
+                else
+                  environment="qa"
+                fi
+                ;;
+              refs/heads/master) 
+                case "$region" in
+                  "antioquia") environment="prd-gana"; ;;
+                  "cap")       environment="prd-cap"; ;;
+                  "tolima")    environment="prd-seapto"; ;;
+                  "huila")     environment="prd-suchance"; ;;
+                  "cauca")     environment="prd-acertemos"; ;;
+                  "boyaca")    environment="prd-jer"; ;;
+                  "santander") environment="prd-laperla"; ;;
+                  "putumayo")  environment="prd-matrixredes"; ;;
+                esac ;;
+            esac
 
-          if [[ "$environment" == "unknown" ]]; then
-            echo -e "\n##vso[task.logissue type=error]⚠️ Environment [$environment] no reconocido"
-            exit 99
-          fi
+            if [[ "$environment" == "unknown" ]]; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ Environment [$environment] no reconocido"
+              exit 99
+            fi
 
-          echo "##vso[task.setvariable variable=environment]$environment"
+            echo "##vso[task.setvariable variable=environment]$environment"
 
-          echo -e "\nℹ️ Varibles de entorno:"
-          echo "Environment: $environment"
+            echo -e "\nℹ️ Varibles de entorno:"
+            echo "Environment: $environment"
         displayName: "⚙️ Generate Environment"
         condition: succeeded()
         env:
           region: ${{ parameters.region }}
           environments: ${{ parameters.environments }}
 
-      - script: |
-          set -e
-          echo -e "\n📦 Cargando al Bucket S3..."
-          APK_NAME="invictus-$(environment)-$(version).apk"
-          BASE_PATH="$(Pipeline.Workspace)/flutter-artifact/flutter"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📦 Cargando al Bucket S3..."
+            APK_NAME="invictus-$(environment)-$(version).apk"
+            BASE_PATH="$(Pipeline.Workspace)/flutter-artifact/flutter"
 
-          echo "APK: $APK_NAME"
-          echo "Environment: $(environment)"
+            echo "APK: $APK_NAME"
+            echo "Environment: $(environment)"
 
-          echo -e "\n📁 Archivos a cargar:"
-          ls -la $BASE_PATH/*
+            echo -e "\n📁 Archivos a cargar:"
+            ls -la $BASE_PATH/*
 
-          aws s3 cp $BASE_PATH/$APK_NAME s3://repository-native/app-seller/android/$(environment)/$APK_NAME --acl public-read
+            aws s3 cp $BASE_PATH/$APK_NAME s3://repository-native/app-seller/android/$(environment)/$APK_NAME --acl public-read
 
-          echo -e "\n✅ Archivos subidos exitosamente."
-          echo "🔗 APK: $APK_NAME"
-          echo -e "\n##[command]🔗 URL: https://repository-native.s3.us-east-1.amazonaws.com/app-seller/android/$(environment)/$APK_NAME"
+            echo -e "\n✅ Archivos subidos exitosamente."
+            echo "🔗 APK: $APK_NAME"
+            echo -e "\n##[command]🔗 URL: https://repository-native.s3.us-east-1.amazonaws.com/app-seller/android/$(environment)/$APK_NAME"
         displayName: "📤 Upload Bucket S3"
         condition: succeeded()
         env:
@@ -118,74 +128,81 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
-      - script: |
-          set -e
-          echo -e "\nℹ️ Enviando Mensaje a SQS..."
-          echo "Cuenta : $(ACCOUNT_ID_INVICTUS)"
-          echo "Version: $(version)"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\nℹ️ Enviando Mensaje a SQS..."
+            echo "Cuenta : $(ACCOUNT_ID_INVICTUS)"
+            echo "Version: $(version)"
 
-          aws sqs send-message \
-            --queue-url https://sqs.us-east-1.amazonaws.com/$(ACCOUNT_ID_INVICTUS)/DynamicStorage \
-            --message-body '{
-              "model": {
-                "parameterName": "VERSION-ANDROID",
-                "parameterDescription": "Parámetro que indica la versión actual Android.",
-                "parameterOrigin": "GLOBAL_PARAMETER",
-                "parameterValue": "$(version)"
-              },
-              "event": "setParameter"
-            }' \
-            --delay-seconds 0
+            aws sqs send-message \
+              --queue-url https://sqs.us-east-1.amazonaws.com/$(ACCOUNT_ID_INVICTUS)/DynamicStorage \
+              --message-body '{
+                "model": {
+                  "parameterName": "VERSION-ANDROID",
+                  "parameterDescription": "Parámetro que indica la versión actual Android.",
+                  "parameterOrigin": "GLOBAL_PARAMETER",
+                  "parameterValue": "$(version)"
+                },
+                "event": "setParameter"
+              }' \
+              --delay-seconds 0
         displayName: "📩 Send Message SQS"
         env:
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
 
-      - script: |
-          DEPLOY_TIME=$(date -d "$BUILD_FINISHTIME -5 hours" "+%Y-%m-%d %I:%M %p")
-          BRANCH_NAME_MULTI=$environments
-          BRANCH_NAME="$(Build.SourceBranchName)"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            DEPLOY_TIME=$(date -d "$BUILD_FINISHTIME -5 hours" "+%Y-%m-%d %I:%M %p")
+            BRANCH_NAME_MULTI=$environments
+            BRANCH_NAME="$(Build.SourceBranchName)"
 
-          if [[ "$BRANCH_NAME" == "master" ]]; then
-            BRANCH_DEPLOY="${red:-red}"
+            if [[ "$BRANCH_NAME" == "master" ]]; then
+              BRANCH_DEPLOY="${red:-red}"
 
-          elif [[ "$BRANCH_NAME" == "develop" && "$BRANCH_NAME_MULTI" == "develop" ]]; then
-            BRANCH_DEPLOY="develop"
+            elif [[ "$BRANCH_NAME" == "develop" && "$BRANCH_NAME_MULTI" == "develop" ]]; then
+              BRANCH_DEPLOY="develop"
 
-          elif [[ "$BRANCH_NAME" == "staging" && "$BRANCH_NAME_MULTI" == "staging" ]]; then
-            BRANCH_DEPLOY="staging"
+            elif [[ "$BRANCH_NAME" == "staging" && "$BRANCH_NAME_MULTI" == "staging" ]]; then
+              BRANCH_DEPLOY="staging"
 
-          else
-            BRANCH_DEPLOY="$BRANCH_NAME_MULTI"
-          fi
+            else
+              BRANCH_DEPLOY="$BRANCH_NAME_MULTI"
+            fi
 
-          payload=$(cat <<EOF
-          {
-            "@type": "MessageCard",
-            "@context": "http://schema.org/extensions",
-            "summary": "Deployment successful",
-            "themeColor": "00FF00",
-            "title": "✅ Deployment exitoso $(Build.SourceBranchName)",
-            "sections": [
-              {
-                "facts": [
-                  { "name": "Pipeline", "value": "$(Build.DefinitionName)" },
-                  { "name": "Branch", "value": "$BRANCH_DEPLOY" },
-                  { "name": "Build", "value": "$(Build.BuildNumber)" },
-                  { "name": "Merged by", "value": "$(Build.RequestedFor)" },
-                  { "name": "Deploy time", "value": "$DEPLOY_TIME" }
-                ],
-                "markdown": true
-              }
-            ]
-          }
-          EOF
-          )
+            payload=$(cat <<EOF
+            {
+              "@type": "MessageCard",
+              "@context": "http://schema.org/extensions",
+              "summary": "Deployment successful",
+              "themeColor": "00FF00",
+              "title": "✅ Deployment exitoso $(Build.SourceBranchName)",
+              "sections": [
+                {
+                  "facts": [
+                    { "name": "Pipeline", "value": "$(Build.DefinitionName)" },
+                    { "name": "Branch", "value": "$BRANCH_DEPLOY" },
+                    { "name": "Build", "value": "$(Build.BuildNumber)" },
+                    { "name": "Merged by", "value": "$(Build.RequestedFor)" },
+                    { "name": "Deploy time", "value": "$DEPLOY_TIME" }
+                  ],
+                  "markdown": true
+                }
+              ]
+            }
+            EOF
+            )
 
-          curl -H "Content-Type: application/json" \
-               -d "$payload" \
-               $(URL_WEBHOOK_TEAMS)
+            curl -H "Content-Type: application/json" \
+                -d "$payload" \
+                $(URL_WEBHOOK_TEAMS)
         displayName: "📢 Post message to Teams"
         env:
           red: ${{ parameters.region }}
diff --git a/pipeline/ci/build/build-electron.yml b/pipeline/ci/build/build-electron.yml
--- a/pipeline/ci/build/build-electron.yml
+++ b/pipeline/ci/build/build-electron.yml
@@ -22,21 +22,24 @@ jobs:
         displayName: "📥 Download Version"
         condition: succeeded()
 
-      - script: |
-          VERSION_FILE="$(Pipeline.Workspace)/versions/electron/version.json"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            VERSION_FILE="$(Pipeline.Workspace)/versions/electron/version.json"
+            echo -e "\n📁 Archivo version.json:"
+            ls -la "$VERSION_FILE"
+            jq . "$VERSION_FILE"
 
-          echo -e "\n📁 Archivo version.json:"
-          ls -la "$VERSION_FILE"
-          jq . "$VERSION_FILE"
-
-          if [[ -f "$VERSION_FILE" ]]; then
-            VERSION=$(jq -r '.version' $VERSION_FILE)
-            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
-            echo "##vso[task.setvariable variable=version]$VERSION"
-          else
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
-            exit 99
-          fi
+            if [[ -f "$VERSION_FILE" ]]; then
+              VERSION=$(jq -r '.version' $VERSION_FILE)
+              echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
+              echo "##vso[task.setvariable variable=version]$VERSION"
+            else
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
+              exit 99
+            fi
         displayName: "📚 Read Version"
         condition: succeeded()
 
@@ -44,6 +47,7 @@ jobs:
         inputs:
           targetType: inline
           script: |
+            set -e
             echo -e "\n🔐 Obteniendo token de AWS CodeArtifact..."
             token=$(aws codeartifact get-authorization-token \
               --domain matrixtech-npm-repository \
@@ -78,25 +82,29 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
-      - script: |
-          CURRENT_BRANCH="$(Build.SourceBranchName)"
-          environment="develop"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            CURRENT_BRANCH="$(Build.SourceBranchName)"
+            environment="develop"
 
-          case "$CURRENT_BRANCH" in 
-            staging) environment="$environment_staging" ;;
-            master) environment="$region" ;;
-          esac
+            case "$CURRENT_BRANCH" in 
+              staging) environment="$environment_staging" ;;
+              master) environment="$region" ;;
+            esac
 
-          cat <<EOF > .env
-          VITE_DOMAIN="${VITE_DOMAIN}"
-          URL_APP="${URL_APP}"
-          TARGET="linux"
-          EOF
+            cat <<EOF > .env
+            VITE_DOMAIN="${VITE_DOMAIN}"
+            URL_APP="${URL_APP}"
+            TARGET="linux"
+            EOF
 
-          echo "##vso[task.setvariable variable=environment]$environment"
-          echo -e "\n📁 File: .env"
-          ls -l .env
-          cat .env
+            echo "##vso[task.setvariable variable=environment]$environment"
+            echo -e "\n📁 File: .env"
+            ls -l .env
+            cat .env
         displayName: "⚙️ Generate .env"
         condition: succeeded()
         env:
@@ -104,116 +112,131 @@ jobs:
           environment_staging: ${{ parameters.environment_staging }}
 
       - task: UsePythonVersion@0
-        displayName: "🔧 Use Python $(pythonVersion)"
         inputs:
           versionSpec: "$(pythonVersion)"
           addToPath: true
+        displayName: "🔧 Use Python $(pythonVersion)"
         condition: succeeded()
 
       - task: UseNode@1
-        displayName: "🔧 Install Nodejs $(nodeVersion)"
         inputs:
           version: "$(nodeVersion)"
+        displayName: "🔧 Install Nodejs $(nodeVersion)"
         condition: succeeded()
 
-      - script: |
-          echo -e "\n📦 Modificando versión en package.json: $(version)"
-          PACKAGE_PATH="$(Build.SourcesDirectory)/package.json"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📦 Modificando versión en package.json: $(version)"
+            PACKAGE_PATH="$(Build.SourcesDirectory)/package.json"
 
-          if [[ -f "$PACKAGE_PATH" ]]; then
-            jq --arg ver "$(version)" '.version = $ver' "$PACKAGE_PATH" > "$PACKAGE_PATH.tmp" && mv "$PACKAGE_PATH.tmp" "$PACKAGE_PATH"
+            if [[ -f "$PACKAGE_PATH" ]]; then
+              jq --arg ver "$(version)" '.version = $ver' "$PACKAGE_PATH" > "$PACKAGE_PATH.tmp" && mv "$PACKAGE_PATH.tmp" "$PACKAGE_PATH"
 
-            echo -e "\n✅ Versión en package.json actualizada correctamente."
-            cat "$PACKAGE_PATH"
-          else
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró el archivo package.json en la ruta [$PACKAGE_PATH]"
-            exit 99
-          fi
+              echo -e "\n✅ Versión en package.json actualizada correctamente."
+              cat "$PACKAGE_PATH"
+            else
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró el archivo package.json en la ruta [$PACKAGE_PATH]"
+              exit 99
+            fi
         displayName: "📝 Update Version package.json"
         condition: succeeded()
 
-      - script: |
-          echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/.pnpmrc"
-          cat <<EOF > "$(System.DefaultWorkingDirectory)/.pnpmrc"
-          node-linker=hoisted
-          shamefully-hoist=true
-          ignore-scripts=false
-          allow-build-script=true
-          strict-peer-dependencies=false
-          EOF
-          ls -l $(System.DefaultWorkingDirectory)/.pnpmrc
-          cat $(System.DefaultWorkingDirectory)/.pnpmrc
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/.pnpmrc"
+            cat <<EOF > "$(System.DefaultWorkingDirectory)/.pnpmrc"
+            node-linker=hoisted
+            shamefully-hoist=true
+            ignore-scripts=false
+            allow-build-script=true
+            strict-peer-dependencies=false
+            EOF
+            ls -l $(System.DefaultWorkingDirectory)/.pnpmrc
+            cat $(System.DefaultWorkingDirectory)/.pnpmrc
 
-          cat $(System.DefaultWorkingDirectory)/.pnpmrc >> $(System.DefaultWorkingDirectory)/.npmrc
-          echo -e "\n✅ Contenido de .pnpmrc anexado a .npmrc correctamente."
+            cat $(System.DefaultWorkingDirectory)/.pnpmrc >> $(System.DefaultWorkingDirectory)/.npmrc
+            echo -e "\n✅ Contenido de .pnpmrc anexado a .npmrc correctamente."
 
-          echo -e "\n⚙️ Instalando dependencias ubuntu..."
-          sudo apt-get update
-          sudo apt-get install -y libcups2-dev
+            echo -e "\n⚙️ Instalando dependencias ubuntu..."
+            sudo apt-get update
+            sudo apt-get install -y libcups2-dev
 
-          echo -e "\n⚙️ Instalando dependencias node..."
-          npm install -g pnpm
-          pnpm install
-          pnpm exec electron-builder install-app-deps
-          pnpm ignored-builds
+            echo -e "\n⚙️ Instalando dependencias node..."
+            npm install -g pnpm
+            pnpm install
+            pnpm exec electron-builder install-app-deps
+            pnpm ignored-builds
 
-          OUTPUT=$(pnpm ls --depth=0 || true)
-          if [[ -z "$OUTPUT" ]]; then
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
-            exit 99
-          else
-            echo -e "\n✅ Dependencias Instaladas:"
-            echo "$OUTPUT"
-          fi
+            OUTPUT=$(pnpm ls --depth=0 || true)
+            if [[ -z "$OUTPUT" ]]; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
+              exit 99
+            else
+              echo -e "\n✅ Dependencias Instaladas:"
+              echo "$OUTPUT"
+            fi
         displayName: "⚙️ Install Dependencies"
         condition: succeeded()
 
-      - script: |
-          set -e
-          echo -e "\n📦 Build Electron..."
-          pnpm run build
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📦 Build Electron..."
+            pnpm run build
         displayName: "📦 Build Electron Linux"
         condition: succeeded()
 
-      - script: |
-          echo -e "\n📝 Validando build electron..."
-          BASE_PATH="$(Build.SourcesDirectory)/release/$(version)/linux"
-          APP_DIR="$BASE_PATH/app"
-          mkdir -p $APP_DIR
-          all_found=true
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📝 Validando build electron..."
+            BASE_PATH="$(Build.SourcesDirectory)/release/$(version)/linux"
+            APP_DIR="$BASE_PATH/app"
+            mkdir -p $APP_DIR
+            all_found=true
 
-          echo -e "\n📂 Directorio: $BASE_PATH"
-          ls -lt $BASE_PATH
-          echo ""
+            echo -e "\n📂 Directorio: $BASE_PATH"
+            ls -lt $BASE_PATH
+            echo ""
 
-          FILES_TO_COPY=(
-            "InvictusUX-$(version).AppImage"
-            "latest-linux.yml"
-          )
+            FILES_TO_COPY=(
+              "InvictusUX-$(version).AppImage"
+              "latest-linux.yml"
+            )
 
-          for file in "${FILES_TO_COPY[@]}"; do
-            source_path="$BASE_PATH/$file"
-            destination_path="$APP_DIR/$file"
+            for file in "${FILES_TO_COPY[@]}"; do
+              source_path="$BASE_PATH/$file"
+              destination_path="$APP_DIR/$file"
 
-            if [[ -f "$source_path" ]]; then
-              cp -f "$source_path" "$destination_path"
-              echo "📂 Copiado: $file -> $destination_path"
+              if [[ -f "$source_path" ]]; then
+                cp -f "$source_path" "$destination_path"
+                echo "📂 Copiado: $file -> $destination_path"
+              else
+                echo "⚠️ Archivo no encontrado: $file"
+                all_found=false
+              fi
+            done
+
+            if ! $all_found; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ Error: archivos requeridos no encontrados."
+              exit 99
             else
-              echo "⚠️ Archivo no encontrado: $file"
-              all_found=false
+              mkdir -p "$(Build.ArtifactStagingDirectory)/release/$(environment)/linux"
+              cp -R $APP_DIR/* "$(Build.ArtifactStagingDirectory)/release/$(environment)/linux"
+
+              echo -e "\n📂 Directorio: $APP_DIR"
+              ls -l $APP_DIR
             fi
-          done
-
-          if ! $all_found; then
-            echo -e "\n##vso[task.logissue type=error]⚠️ Error: archivos requeridos no encontrados."
-            exit 99
-          else
-            mkdir -p "$(Build.ArtifactStagingDirectory)/release/$(environment)/linux"
-            cp -R $APP_DIR/* "$(Build.ArtifactStagingDirectory)/release/$(environment)/linux"
-
-            echo -e "\n📂 Directorio: $APP_DIR"
-            ls -l $APP_DIR
-          fi
         displayName: "🔍 Validate Build"
         condition: succeeded()
 
@@ -238,7 +261,7 @@ jobs:
       - template: ../../variables/groups-transversal-variables-electron.yml
         parameters:
           region: ${{ parameters.region }}
-          environments: ${{ parameters.environments }}
+          environment_staging: ${{ parameters.environment_staging }}
 
     steps:
       - task: DownloadBuildArtifacts@0
@@ -249,12 +272,10 @@ jobs:
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "📚 Read Version"
         inputs:
           targetType: inline
           script: |
             $versionFile = "$(Pipeline.Workspace)\versions\electron\version.json"
-
             Write-Host "`n📁 Archivo version.json:"
             Get-ChildItem -Path $versionFile | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
             Get-Content -Path $versionFile
@@ -268,10 +289,10 @@ jobs:
               Write-Output "`n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para app"
               exit 99
             }
+        displayName: "📚 Read Version"
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "🔐 Setup CodeArtifact & npm config"
         inputs:
           targetType: inline
           script: |
@@ -307,6 +328,7 @@ jobs:
             registry=$repoUrl
             "@ | Set-Content -Encoding UTF8 -Path $npmrcPath
             Get-Item $npmrcPath | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
+        displayName: "🔐 Setup CodeArtifact & npm config"
         condition: succeeded()
         env:
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
@@ -314,7 +336,6 @@ jobs:
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
       - task: PowerShell@2
-        displayName: "⚙️ Generate .env"
         inputs:
           targetType: inline
           script: |
@@ -336,26 +357,26 @@ jobs:
             Write-Host "`n📁 File: .env"
             Get-Item .env | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
             Get-Content .env
+        displayName: "⚙️ Generate .env"
         condition: succeeded()
         env:
           region: ${{ parameters.region }}
           environment_staging: ${{ parameters.environment_staging }}
 
       - task: UsePythonVersion@0
-        displayName: "🔧 Use Python $(pythonVersion)"
         inputs:
           versionSpec: "$(pythonVersion)"
           addToPath: true
+        displayName: "🔧 Use Python $(pythonVersion)"
         condition: succeeded()
 
       - task: UseNode@1
-        displayName: "🔧 Install Nodejs $(nodeVersion)"
         inputs:
           version: "$(nodeVersion)"
+        displayName: "🔧 Install Nodejs $(nodeVersion)"
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "📝 Update Version package.json"
         inputs:
           targetType: inline
           script: |
@@ -373,10 +394,10 @@ jobs:
               Write-Output "`n##vso[task.logissue type=error]⚠️ No se encontro el archivo package.json en la ruta [$packagePath]"
               exit 99
             }
+        displayName: "📝 Update Version package.json"
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "🧹 Remove BOM from package.json"
         inputs:
           targetType: inline
           script: |
@@ -394,10 +415,10 @@ jobs:
                 Write-Output "`n##vso[task.logissue type=error]⚠️ Error: package.json no se encontró en $filePath"
                 exit 99
             }
+        displayName: "🧹 Remove BOM from package.json"
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "⚙️ Install Dependencies"
         inputs:
           targetType: inline
           script: |
@@ -431,20 +452,20 @@ jobs:
               Write-Host "`n✅ Dependencias Instaladas:"
               Write-Host $output
             }
+        displayName: "⚙️ Install Dependencies"
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "📦 Build Electron Windows"
         inputs:
           targetType: " inline"
           script: |
             $ErrorActionPreference = "Stop"
             Write-Host "`n📦 Build Electron..."
             pnpm run build
+        displayName: "📦 Build Electron Windows"
         condition: succeeded()
 
       - task: PowerShell@2
-        displayName: "🔍 Validate Build"
         inputs:
           targetType: " inline"
           script: |
@@ -488,6 +509,7 @@ jobs:
               Write-Host "`n📂 Directorio: $APP_DIR"
               Get-ChildItem "$APP_DIR" | Select-Object Mode, LastWriteTime, Length, Name | Format-Table
             }
+        displayName: "🔍 Validate Build"
         condition: succeeded()
 
       - task: PublishBuildArtifacts@1
diff --git a/pipeline/ci/build/build-frontend.yml b/pipeline/ci/build/build-frontend.yml
--- a/pipeline/ci/build/build-frontend.yml
+++ b/pipeline/ci/build/build-frontend.yml
@@ -1,5 +1,5 @@
 jobs:
-  - job: build_micro_frontend_${{ parameters.region }}
+  - job: build_microfrontend_${{ parameters.region }}
     displayName: "📦 build"
     pool:
       name: "Azure Pipelines"
@@ -25,34 +25,41 @@ jobs:
         displayName: "📥 Download Version"
         condition: succeeded()
 
-      - script: |
-          VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/$(msName)/version.json"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/$(msName)/version.json"
+            echo -e "\n📁 Archivo version.json:"
+            ls -la "$VERSION_FILE"
+            jq . "$VERSION_FILE"
 
-          echo -e "\n📁 Archivo version.json:"
-          ls -la "$VERSION_FILE"
-          jq . "$VERSION_FILE"
-
-          if [[ -f "$VERSION_FILE" ]]; then
-            VERSION=$(jq -r '.version' $VERSION_FILE)
-            echo -e "\n🚀 Versión detectada para $(msName): $VERSION"
-            echo "##vso[task.setvariable variable=msVersion]$VERSION"
-          else
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró archivo de versión para: $(msName)" 
-            exit 99
-          fi
+            if [[ -f "$VERSION_FILE" ]]; then
+              VERSION=$(jq -r '.version' $VERSION_FILE)
+              echo -e "\n🚀 Versión detectada para $(msName): $VERSION"
+              echo "##vso[task.setvariable variable=msVersion]$VERSION"
+            else
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró archivo de versión para: $(msName)" 
+              exit 99
+            fi
         displayName: "📚 Read Version"
         condition: succeeded()
 
-      - script: |
-          if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
-            fileselect=app-legacy
-            echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
-            echo "##vso[task.setvariable variable=file]$fileselect"
-          else
-            fileselect=apps
-            echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
-            echo "##vso[task.setvariable variable=file]$fileselect"
-          fi
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
+              fileselect=app-legacy
+              echo -e "\nℹ️ Ruta de archivo del microfrontend: $fileselect"
+              echo "##vso[task.setvariable variable=file]$fileselect"
+            else
+              fileselect=apps
+              echo -e "\nℹ️ Ruta de archivo del microfrontend: $fileselect"
+              echo "##vso[task.setvariable variable=file]$fileselect"
+            fi
         displayName: "📂 Select Directory"
         condition: succeeded()
 
@@ -60,6 +67,7 @@ jobs:
         inputs:
           targetType: inline
           script: |
+            set -e
             echo "🔐 Obteniendo token de AWS CodeArtifact..."
             token=$(aws codeartifact get-authorization-token \
               --domain matrixtech-npm-repository \
@@ -85,7 +93,7 @@ jobs:
             //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
             registry=$REPO_URL
             EOF
-            
+
             echo -e "\n✅ .npmrc generado"
             ls -l $npmrcPath
         displayName: "🔐 Setup CodeArtifact & npm config"
@@ -95,114 +103,133 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
-      - script: |
-          echo -e "\n📁 Archivo .env.local: app-administration-vue2"
-          printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
-          printenv | grep "^ADMIN_" | sed "s/^ADMIN_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
-          ls -l app-legacy/app-administration-vue2/.env.local
-          cat app-legacy/app-administration-vue2/.env.local
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📁 Archivo .env.local: app-administration-vue2"
+            printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
+            printenv | grep "^ADMIN_" | sed "s/^ADMIN_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-administration-vue2/.env.local
+            ls -l app-legacy/app-administration-vue2/.env.local
+            cat app-legacy/app-administration-vue2/.env.local
 
-          echo -e "\n📁 Archivo .env.local: app-sellers-vue2"
-          printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
-          printenv | grep "^SELLERS_" | sed "s/^SELLERS_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
-          ls -l app-legacy/app-sellers-vue2/.env.local
-          cat app-legacy/app-sellers-vue2/.env.local
+            echo -e "\n📁 Archivo .env.local: app-sellers-vue2"
+            printenv | grep "^VUE2_" | sed "s/^VUE2_//" > $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
+            printenv | grep "^SELLERS_" | sed "s/^SELLERS_//" >> $(System.DefaultWorkingDirectory)/app-legacy/app-sellers-vue2/.env.local
+            ls -l app-legacy/app-sellers-vue2/.env.local
+            cat app-legacy/app-sellers-vue2/.env.local
 
-          echo -e "\n📁 Archivo .env: invictus"
-          printenv | grep -i "^INVICTUS_" |sed "s/^INVICTUS_//" > $(System.DefaultWorkingDirectory)/apps/invictus/.env
-          ls -l apps/invictus/.env
-          cat apps/invictus/.env
+            echo -e "\n📁 Archivo .env: invictus"
+            printenv | grep -i "^INVICTUS_" |sed "s/^INVICTUS_//" > $(System.DefaultWorkingDirectory)/apps/invictus/.env
+            ls -l apps/invictus/.env
+            cat apps/invictus/.env
 
-          echo -e "\n📁 Archivos .env para el path raiz"
-          printenv | grep "^ROOT_" | sed "s/^ROOT_//" > $(System.DefaultWorkingDirectory)/.env
-          ls -l .env
-          cat .env
+            echo -e "\n📁 Archivos .env para el path raiz"
+            printenv | grep "^ROOT_" | sed "s/^ROOT_//" > $(System.DefaultWorkingDirectory)/.env
+            ls -l .env
+            cat .env
         displayName: "⚙️ Generate .env"
         condition: succeeded()
 
-      - script: |
-          echo -e "\n📁 Archivos .env: $(msName)"
-          printenv | grep -i "^$(msName)_" |sed -E "s/^($(msName))_//I" > $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
-          cat apps/invictus/.env >> $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
-          ls -l apps/$(msName)/.env
-          cat apps/$(msName)/.env
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📁 Archivos .env: $(msName)"
+            printenv | grep -i "^$(msName)_" |sed -E "s/^($(msName))_//I" > $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
+            cat apps/invictus/.env >> $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.env
+            ls -l apps/$(msName)/.env
+            cat apps/$(msName)/.env
         displayName: "⚙️ Generate $(msName) .env"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'))
 
-      - script: |
-          cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
-          echo "🔧 Actualizando versión en $(file)/$(msName)/package.json: $(msVersion)"
-          jq --arg version "$(msVersion)" '.version = $version' package.json > tmp.json && mv tmp.json package.json
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
+            echo "🔧 Actualizando versión en $(file)/$(msName)/package.json: $(msVersion)"
+            jq --arg version "$(msVersion)" '.version = $version' package.json > tmp.json && mv tmp.json package.json
 
-          echo -e "\n📁 File package.json:"      
-          cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/package.json
+            echo -e "\n📁 File package.json:"      
+            cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/package.json
         displayName: "📝 Update Version package.json"
         condition: succeeded()
 
       - task: UseNode@1
-        displayName: "🔧 Install Nodejs $(nodeVersion)"
         inputs:
           version: "$(nodeVersion)"
+        displayName: "🔧 Install Nodejs $(nodeVersion)"
         condition: succeeded()
 
-      - script: |
-          echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
-          cat <<EOF > "$(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
-          node-linker=hoisted
-          shamefully-hoist=true
-          ignore-scripts=false
-          allow-build-script=true
-          strict-peer-dependencies=false
-          EOF
-          ls -l $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
-          cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📁 Generando archivo .pnpmrc en: $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
+            cat <<EOF > "$(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc"
+            node-linker=hoisted
+            shamefully-hoist=true
+            ignore-scripts=false
+            allow-build-script=true
+            strict-peer-dependencies=false
+            EOF
+            ls -l $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
+            cat $(System.DefaultWorkingDirectory)/$(file)/$(msName)/.pnpmrc
 
-          cd $(System.DefaultWorkingDirectory)
-          echo -e "\n⚙️ Instalando dependencias node..."
-          npm install -g pnpm
-          pnpm install
+            cd $(System.DefaultWorkingDirectory)
+            echo -e "\n⚙️ Instalando dependencias node..."
+            npm install -g pnpm
+            pnpm install
 
-          OUTPUT=$(pnpm ls --depth=0 || true)
-          if [[ -z "$OUTPUT" ]]; then
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
-            exit 99
-          else
-            echo -e "\n✅ Dependencias Instaladas:"
-            echo "$OUTPUT"
-          fi
+            OUTPUT=$(pnpm ls --depth=0 || true)
+            if [[ -z "$OUTPUT" ]]; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
+              exit 99
+            else
+              echo -e "\n✅ Dependencias Instaladas:"
+              echo "$OUTPUT"
+            fi
         displayName: "⚙️ Install Dependencies"
         condition: succeeded()
 
-      - script: |
-          set -e
-          echo -e "\n📦 Build MicroFrontend..."
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📦 Build MicroFrontend..."
 
-          if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
-            cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
-            pnpm run build
-          else
-            pnpm run build --filter=...$(msName)
-          fi
-
-          DIST_PATH="$(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist"
-
-          if [[ ! -d "$DIST_PATH" ]] || [[ -z "$(ls -A "$DIST_PATH" 2>/dev/null)" ]]; then
-            echo -e "\n##vso[task.logissue type=error]⚠️ Error: No se generó el build o la carpeta dist está vacía." 
-            exit 99
-          else
-            CURRENT_BRANCH=$(echo $(Build.SourceBranch))
-            if [[ "$CURRENT_BRANCH" =~ ^refs/heads/(develop|staging)$ ]]; then
-              mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$environments"
-              cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$environments/$(msName)
+            if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
+              cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
+              pnpm run build
             else
-              mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$region"
-              cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$region/$(msName)
+              pnpm run build --filter=...$(msName)
             fi
-            echo -e "\n✅ Build generado correctamente en: $DIST_PATH"
-            ls -l "$DIST_PATH"
-          fi
+
+            DIST_PATH="$(System.DefaultWorkingDirectory)/$(file)/$(msName)/dist"
+
+            if [[ ! -d "$DIST_PATH" ]] || [[ -z "$(ls -A "$DIST_PATH" 2>/dev/null)" ]]; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ Error: No se generó el build o la carpeta dist está vacía." 
+              exit 99
+            else
+              CURRENT_BRANCH=$(echo $(Build.SourceBranch))
+              if [[ "$CURRENT_BRANCH" =~ ^refs/heads/(develop|staging)$ ]]; then
+                mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$environments"
+                cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$environments/$(msName)
+              else
+                mkdir -p "$(Build.ArtifactStagingDirectory)/dists/$region"
+                cp -R $DIST_PATH $(Build.ArtifactStagingDirectory)/dists/$region/$(msName)
+              fi
+              echo -e "\n✅ Build generado correctamente en: $DIST_PATH"
+              ls -l "$DIST_PATH"
+            fi
         displayName: "📦 Build $(msName)"
         condition: succeeded()
         env:
diff --git a/pipeline/ci/pre-build/changes-files-frontend.yml b/pipeline/ci/pre-build/changes-files-frontend.yml
--- a/pipeline/ci/pre-build/changes-files-frontend.yml
+++ b/pipeline/ci/pre-build/changes-files-frontend.yml
@@ -1,5 +1,5 @@
 jobs:
-  - job: "pre_build_micro_fronted"
+  - job: "pre_build_microfrontend"
     displayName: "🔍 detect changes microfrontend"
     pool:
       name: "Azure Pipelines"
@@ -14,133 +14,56 @@ jobs:
         persistCredentials: true
         fetchTags: false
 
-      - script: |
-          echo "🔍 Validando ejecucion..."
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo "🔍 Validando ejecucion..."
 
-          case "$(Build.Reason)" in
-            "PullRequest")
-              echo -e "\nℹ️ Ejecucion Valida por: PullRequest"
-              echo "Branch: $(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')"
-              echo "Build Reason: $(Build.Reason)"
-              echo "Pull Request: $(System.PullRequest.PullRequestId)"
-              ;;
-            "IndividualCI")
-              echo -e "\nℹ️ Ejecucion Valida por: IndividualCI"
-              echo "Branch: $(echo "$(Build.SourceBranch)" | sed 's#refs/heads/##')"
-              echo "Build Reason: $(Build.Reason)"
-              ;;
-            *)
-              echo -e "\n##vso[task.logissue type=error]⚠️ Ejecucion [$(Build.Reason)] no valida."
-              echo "##vso[task.logissue type=error] Debe ejecutarse solo por PullRequest o IndividualCI."
-              exit 99
-              ;;
-          esac
+            case "$(Build.Reason)" in
+              "PullRequest")
+                echo -e "\nℹ️ Ejecucion Valida por: PullRequest"
+                echo "Branch: $(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')"
+                echo "Build Reason: $(Build.Reason)"
+                echo "Pull Request: $(System.PullRequest.PullRequestId)"
+                ;;
+              "IndividualCI")
+                echo -e "\nℹ️ Ejecucion Valida por: IndividualCI"
+                echo "Branch: $(echo "$(Build.SourceBranch)" | sed 's#refs/heads/##')"
+                echo "Build Reason: $(Build.Reason)"
+                ;;
+              *)
+                echo -e "\n##vso[task.logissue type=error]⚠️ Ejecucion [$(Build.Reason)] no valida."
+                echo "##vso[task.logissue type=error] Debe ejecutarse solo por PullRequest o IndividualCI."
+                exit 99
+                ;;
+            esac
         displayName: "🧩 Validate Execution (Auto/Manual)"
         condition: succeeded()
 
-      - script: |
-          az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
         displayName: "📌 Set Azure DevOps organization"
         condition: succeeded()
 
-      - script: |
-          echo "⚙️ Configurando organización y proyecto por defecto"
-          az devops configure --defaults organization=https://dev.azure.com/ux-technology project=$(System.TeamProject)
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo "⚙️ Configurando organización y proyecto por defecto"
+            az devops configure --defaults organization=https://dev.azure.com/ux-technology project=$(System.TeamProject)
 
-          case "$(Build.Reason)" in
-            "PullRequest")
-              SOURCE_BRANCH=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
-              TARGET_BRANCH=$(echo "$(System.PullRequest.TargetBranch)" | sed 's#refs/heads/##')
-              CURRENT_BRANCH=$SOURCE_BRANCH
-
-              echo -e "\n🔍 Validando nombre de la rama: $CURRENT_BRANCH"
-              if [[ ! "$CURRENT_BRANCH" =~ ^(feature\/[a-zA-Z0-9._-]+|hotfix\/[a-zA-Z0-9._-]+|develop|staging|master)$ ]]; then
-                echo -e "\n##vso[task.logissue type=error]⚠️ Error: la rama '$CURRENT_BRANCH' no cumple con el nombramiento."
-                echo "##vso[task.logissue type=error] Usa: feature/*, hotfix/*, develop, staging o master"
-                exit 99
-              fi
-
-              cd $(Build.SourcesDirectory)
-              clean_branch=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
-              git checkout $clean_branch
-              git reset --hard HEAD
-
-              git fetch origin $TARGET_BRANCH
-
-              BASE=$(git merge-base HEAD origin/$TARGET_BRANCH)
-
-              echo "📌 Merge base detectado: $BASE"
-
-              changed_files=$(git diff --name-only $BASE HEAD)
-              packages_changed=$(echo "$changed_files" | grep "^packages/" || true)
-
-              apps=$(echo "$changed_files" | grep -E "^apps/|^app-legacy/" | cut -d '/' -f1,2 | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
-
-              if [[ -n "$packages_changed" ]]; then
-                apps=$(printf "%s\ninvictus" "$apps" | sort -u)
-              fi
-
-              if [[ -z "$apps" ]]; then
-                echo -e "\n##vso[task.logissue type=error]⚠️ No se detectaron cambios en apps. Cancelando ejecución del pipeline."
-                exit 99
-              fi
-              
-              echo "🔍 Apps modificadas detectadas:"
-              echo "${apps[@]}"
-              apps_json=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s .)
-
-              if [[ "$SOURCE_BRANCH" == feature/* || "$SOURCE_BRANCH" == hotfix/* ]]; then
-                echo -e "\n🔗 Creando ejecucion pipeline"
-                pipeline_output=$(az pipelines run \
-                  --name "$(Build.Repository.Name)" \
-                  --branch "$CURRENT_BRANCH" \
-                  --parameters pr_id="$(System.PullRequest.PullRequestId)" apps="$apps_json" \
-                  --output json)
-                echo "$pipeline_output" | jq
-
-                run_id=$(echo "$pipeline_output" | jq -r '.id')              
-                echo -e "\n##[command]🌐 Build Results: https://dev.azure.com/ux-technology/Invictus/_build/results?buildId=$run_id"
-              fi
-
-              #
-              ## Cuando se realiza un PR de stagin a master no se debe corre el check por eso, se habilita la propiedad para que continue sin problemas el PR 
-              #
-              if [[ ("$SOURCE_BRANCH" == "develop" && "$TARGET_BRANCH" == "staging") || ("$SOURCE_BRANCH" == "staging" && "$TARGET_BRANCH" == "master") ]]; then
-                ORGANIZATION=$(System.CollectionUri)
-                PROJECT=$(System.TeamProject)
-                STATE="succeeded"
-                DESCRIPTION="Build completed successfully"
-
-                ITERATION_ID=$(curl -s \
-                  -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
-                  "$ORGANIZATION/$PROJECT/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/iterations?api-version=7.1-preview.1" \
-                  | jq '.value[-1].id')
-
-                echo -e "\n📡 Reportando resultado a Azure DevOps..."
-                echo "Estado: $STATE"
-                echo "Descripcion: $DESCRIPTION"
-                echo "Pull Request Id: $(System.PullRequest.PullRequestId)"
-                echo "Iteration Id: $ITERATION_ID"
-
-                cat > body.json <<< "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":{\"name\":\"build-check\",\"genre\":\"pipeline\"},\"iterationId\":$ITERATION_ID}"
-                echo -e "\n📁 File: body.json"
-                jq . body.json
-
-                API_URL="$ORGANIZATION/$PROJECT/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/statuses?api-version=7.1-preview.1"
-                echo -e "\n##[command]🌐 Build Results: $API_URL"
-
-                curl -s \
-                  -X POST "$API_URL" \
-                  -H "Content-Type: application/json" \
-                  -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
-                  --data-binary "@body.json"
-              fi
-              ;;
-            "IndividualCI")
-                cd $(Build.SourcesDirectory)
-                CURRENT_BRANCH="$(echo "$(Build.SourceBranch)" | sed 's#refs/heads/##')"
-                git checkout $CURRENT_BRANCH
-                git reset --hard HEAD
+            case "$(Build.Reason)" in
+              "PullRequest")
+                SOURCE_BRANCH=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
+                TARGET_BRANCH=$(echo "$(System.PullRequest.TargetBranch)" | sed 's#refs/heads/##')
+                CURRENT_BRANCH=$SOURCE_BRANCH
 
                 echo -e "\n🔍 Validando nombre de la rama: $CURRENT_BRANCH"
                 if [[ ! "$CURRENT_BRANCH" =~ ^(feature\/[a-zA-Z0-9._-]+|hotfix\/[a-zA-Z0-9._-]+|develop|staging|master)$ ]]; then
@@ -149,10 +72,21 @@ jobs:
                   exit 99
                 fi
 
-                echo "🔍 Comparando cambios entre: $CURRENT_BRANCH ... $CURRENT_BRANCH"
-                packages_changed=$(git diff --name-only HEAD~1 HEAD | grep "^packages/")
+                cd $(Build.SourcesDirectory)
+                clean_branch=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
+                git checkout $clean_branch
+                git reset --hard HEAD
 
-                apps=$(git diff --name-only HEAD~1 HEAD | grep -E "^apps/|^app-legacy/" | cut -d '/' -f1,2 | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
+                git fetch origin $TARGET_BRANCH
+
+                BASE=$(git merge-base HEAD origin/$TARGET_BRANCH)
+
+                echo "📌 Merge base detectado: $BASE"
+
+                changed_files=$(git diff --name-only $BASE HEAD)
+                packages_changed=$(echo "$changed_files" | grep "^packages/" || true)
+
+                apps=$(echo "$changed_files" | grep -E "^apps/|^app-legacy/" | cut -d '/' -f1,2 | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
 
                 if [[ -n "$packages_changed" ]]; then
                   apps=$(printf "%s\ninvictus" "$apps" | sort -u)
@@ -162,28 +96,106 @@ jobs:
                   echo -e "\n##vso[task.logissue type=error]⚠️ No se detectaron cambios en apps. Cancelando ejecución del pipeline."
                   exit 99
                 fi
-
+                
                 echo "🔍 Apps modificadas detectadas:"
                 echo "${apps[@]}"
                 apps_json=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s .)
 
-                echo -e "\n🔗 Creando ejecucion pipeline"
-                pipeline_output=$(az pipelines run \
-                  --name "$(Build.Repository.Name)" \
-                  --branch "$CURRENT_BRANCH" \
-                  --parameters pr_id="0" apps="$apps_json" \
-                  --output json)
-                echo "$pipeline_output" | jq
+                if [[ "$SOURCE_BRANCH" == feature/* || "$SOURCE_BRANCH" == hotfix/* ]]; then
+                  echo -e "\n🔗 Creando ejecucion pipeline"
+                  pipeline_output=$(az pipelines run \
+                    --name "$(Build.Repository.Name)" \
+                    --branch "$CURRENT_BRANCH" \
+                    --parameters pr_id="$(System.PullRequest.PullRequestId)" apps="$apps_json" \
+                    --output json)
+                  echo "$pipeline_output" | jq
 
-                run_id=$(echo "$pipeline_output" | jq -r '.id')              
-                echo -e "\n##[command]🌐 Build Results: https://dev.azure.com/ux-technology/Invictus/_build/results?buildId=$run_id"
-              ;;
-            *)
-              echo -e "\n##vso[task.logissue type=error]⚠️ Ejecucion [$(Build.Reason)] no valida."
-              echo "##vso[task.logissue type=error] Debe ejecutarse solo por PullRequest o IndividualCI."
-              exit 99
-              ;;
-          esac
+                  run_id=$(echo "$pipeline_output" | jq -r '.id')              
+                  echo -e "\n##[command]🌐 Build Results: https://dev.azure.com/ux-technology/Invictus/_build/results?buildId=$run_id"
+                fi
+
+                #
+                ## Cuando se realiza un PR de stagin a master no se debe corre el check por eso, se habilita la propiedad para que continue sin problemas el PR 
+                #
+                if [[ ("$SOURCE_BRANCH" == "develop" && "$TARGET_BRANCH" == "staging") || ("$SOURCE_BRANCH" == "staging" && "$TARGET_BRANCH" == "master") ]]; then
+                  ORGANIZATION=$(System.CollectionUri)
+                  PROJECT=$(System.TeamProject)
+                  STATE="succeeded"
+                  DESCRIPTION="Build completed successfully"
+
+                  ITERATION_ID=$(curl -s \
+                    -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
+                    "$ORGANIZATION/$PROJECT/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/iterations?api-version=7.1-preview.1" \
+                    | jq '.value[-1].id')
+
+                  echo -e "\n📡 Reportando resultado a Azure DevOps..."
+                  echo "Estado: $STATE"
+                  echo "Descripcion: $DESCRIPTION"
+                  echo "Pull Request Id: $(System.PullRequest.PullRequestId)"
+                  echo "Iteration Id: $ITERATION_ID"
+
+                  cat > body.json <<< "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":{\"name\":\"build-check\",\"genre\":\"pipeline\"},\"iterationId\":$ITERATION_ID}"
+                  echo -e "\n📁 File: body.json"
+                  jq . body.json
+
+                  API_URL="$ORGANIZATION/$PROJECT/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/statuses?api-version=7.1-preview.1"
+                  echo -e "\n##[command]🌐 Build Results: $API_URL"
+
+                  curl -s \
+                    -X POST "$API_URL" \
+                    -H "Content-Type: application/json" \
+                    -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
+                    --data-binary "@body.json"
+                fi
+                ;;
+              "IndividualCI")
+                  cd $(Build.SourcesDirectory)
+                  CURRENT_BRANCH="$(echo "$(Build.SourceBranch)" | sed 's#refs/heads/##')"
+                  git checkout $CURRENT_BRANCH
+                  git reset --hard HEAD
+
+                  echo -e "\n🔍 Validando nombre de la rama: $CURRENT_BRANCH"
+                  if [[ ! "$CURRENT_BRANCH" =~ ^(feature\/[a-zA-Z0-9._-]+|hotfix\/[a-zA-Z0-9._-]+|develop|staging|master)$ ]]; then
+                    echo -e "\n##vso[task.logissue type=error]⚠️ Error: la rama '$CURRENT_BRANCH' no cumple con el nombramiento."
+                    echo "##vso[task.logissue type=error] Usa: feature/*, hotfix/*, develop, staging o master"
+                    exit 99
+                  fi
+
+                  echo "🔍 Comparando cambios entre: $CURRENT_BRANCH ... $CURRENT_BRANCH"
+                  packages_changed=$(git diff --name-only HEAD~1 HEAD | grep "^packages/")
+
+                  apps=$(git diff --name-only HEAD~1 HEAD | grep -E "^apps/|^app-legacy/" | cut -d '/' -f1,2 | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
+
+                  if [[ -n "$packages_changed" ]]; then
+                    apps=$(printf "%s\ninvictus" "$apps" | sort -u)
+                  fi
+
+                  if [[ -z "$apps" ]]; then
+                    echo -e "\n##vso[task.logissue type=error]⚠️ No se detectaron cambios en apps. Cancelando ejecución del pipeline."
+                    exit 99
+                  fi
+
+                  echo "🔍 Apps modificadas detectadas:"
+                  echo "${apps[@]}"
+                  apps_json=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s .)
+
+                  echo -e "\n🔗 Creando ejecucion pipeline"
+                  pipeline_output=$(az pipelines run \
+                    --name "$(Build.Repository.Name)" \
+                    --branch "$CURRENT_BRANCH" \
+                    --parameters pr_id="0" apps="$apps_json" \
+                    --output json)
+                  echo "$pipeline_output" | jq
+
+                  run_id=$(echo "$pipeline_output" | jq -r '.id')              
+                  echo -e "\n##[command]🌐 Build Results: https://dev.azure.com/ux-technology/Invictus/_build/results?buildId=$run_id"
+                ;;
+              *)
+                echo -e "\n##vso[task.logissue type=error]⚠️ Ejecucion [$(Build.Reason)] no valida."
+                echo "##vso[task.logissue type=error] Debe ejecutarse solo por PullRequest o IndividualCI."
+                exit 99
+                ;;
+            esac
         displayName: "🔍 Detect Changed Files MS"
         condition: succeeded()
         env:
