Update frontend deploy

diff --git a/pipeline/cd/deploy/deploy-frontend.yml b/pipeline/cd/deploy/deploy-frontend.yml
--- a/pipeline/cd/deploy/deploy-frontend.yml
+++ b/pipeline/cd/deploy/deploy-frontend.yml
@@ -71,50 +71,101 @@ jobs:
         env:
           region: ${{ parameters.region }}
 
+      - script: |
+          CLOUDFRONT_VAR_NAME=$(echo "$(msName)" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
+          CLOUDFRONT_VAR_NAME=CLOUDFRONT_ID_$CLOUDFRONT_VAR_NAME
+          CLOUDFRONT_ID="${!CLOUDFRONT_VAR_NAME}"
 
+          echo -e "\nℹ️ CLOUDFRONT: $(msName)"
+          echo "CLOUDFRONT_ID: $CLOUDFRONT_ID"
+          echo "CLOUDFRONT_VAR_NAME: $CLOUDFRONT_VAR_NAME"
 
+          if [[ -z "$CLOUDFRONT_ID" ]] || [[ -z "$CLOUDFRONT_VAR_NAME" ]]; then
+            echo -e "\n##vso[task.logissue type=error]⚠️ CLOUDFRONT_ID o CLOUDFRONT_VAR_NAME no reconocidos"
+            echo -e "##vso[task.logissue type=error]⚠️ CLOUDFRONT_ID: $CLOUDFRONT_ID"
+            echo -e "##vso[task.logissue type=error]⚠️ CLOUDFRONT_VAR_NAME: $CLOUDFRONT_VAR_NAME"
+            exit 99
+          else
+            echo "##vso[task.setvariable variable=CLOUDFRONT_ID]$CLOUDFRONT_ID"
+          fi
+        displayName: "📌 Set CloudFront ID"
+        condition: succeeded()
 
       - script: |
-          set -e
-          echo -e "\n📦 Cargando al Bucket S3..."
+          echo -e "\nℹ️ Obteniendo CloudFront Distribution para: $(CLOUDFRONT_ID)..."
+          aws cloudfront get-distribution-config --id $(CLOUDFRONT_ID) --region $(AWS_DEFAULT_REGION) > $(CLOUDFRONT_ID).json
 
-          BASE_PATH="$(Pipeline.Workspace)/downloaded-dists/dists//$(msName)"
-
-          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
-          ls -l "$BASE_PATH"
-
-          aws s3 cp "$BASE_PATH" "s3://electron-app-$(ACCOUNT_ID_INVIC)/linux/" --recursive
-
-          echo -e "\n✅ Archivos subidos exitosamente."
-          echo "🔗 APP: InvictusUX-$(msVersion).AppImage"
-          echo "🔗 URL: https://electron-app-$(ACCOUNT_ID_INVIC).s3.us-east-1.amazonaws.com/InvictusUX-$(msVersion).AppImage"
-
-        displayName: "🐧 Upload Bucket S3 Linux"
-        condition: succeeded()
+          echo -e "\n📂 Archivo: $(CLOUDFRONT_ID).json"
+          cat $(CLOUDFRONT_ID).json
+        displayName: "📡 Get CloudFront Distribution"
         env:
-          region: ${{ parameters.region }}
-
-          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
 
       - script: |
-          set -e
-          echo -e "\n📦 Cargando al Bucket S3..."
+          echo -e "\nℹ️ Insertando nueva versión en CloudFront Distribution: $(CLOUDFRONT_ID)..."
+          echo -e "\nVersion a actualizar: $(msVersion)"
 
-          BASE_PATH="$(Pipeline.Workspace)/electron-artifacts/electron/windows"
-          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
-          ls -l "$BASE_PATH"
+          jq --arg v "/$(msVersion)" '.DistributionConfig.Origins.Items[0].OriginPath = $v' "$(CLOUDFRONT_ID).json" > "new-$(CLOUDFRONT_ID).json"
 
-          aws s3 cp "$BASE_PATH" "s3://electron-app-$(ACCOUNT_ID_INVIC)/windows/" --recursive
+          echo -e "\n📂 Archivo: new-$(CLOUDFRONT_ID).json"
+          cat new-$(CLOUDFRONT_ID).json
+        displayName: "🔖 Insert New Version"
 
-          echo -e "\n✅ Archivos subidos exitosamente."
-          echo "🔗 APP: InvictusUX Setup $(msVersion).exe"
-          echo "🔗 URL: https://electron-app-$(ACCOUNT_ID_INVIC).s3.us-east-1.amazonaws.com/InvictusUX+Setup+$(msVersion).exe"
+      - script: |
+          echo -e "\nℹ️ Actualizando CloudFront Distribution: $(CLOUDFRONT_ID)..."
+          ETAG=$(jq -r '.ETag' $(CLOUDFRONT_ID).json)
+          echo -e "\nCloudFront ETag: \n$ETAG"
 
-        displayName: "🖥️ Upload Bucket S3 Windows"
-        condition: succeeded()
+          jq '.DistributionConfig' "new-$(CLOUDFRONT_ID).json" > "new-$(CLOUDFRONT_ID).json"
+          echo -e "\n📂 Archivo: new-$(CLOUDFRONT_ID).json"
+          cat new-$(CLOUDFRONT_ID).json
+
+          aws cloudfront update-distribution --id $(CLOUDFRONT_ID) --region $AWS_DEFAULT_REGION --if-match "$ETAG" --distribution-config file://new-$(CLOUDFRONT_ID).json
+        displayName: "🔄 Update CloudFront Distribution"
         env:
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
           AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      - script: |
+          echo -e "\n⏳ Esperando que CloudFront Distribution $(CLOUDFRONT_ID) se propague..."
+
+          while true; do
+            STATUS=$(aws cloudfront get-distribution --id $(CLOUDFRONT_ID) --region $AWS_DEFAULT_REGION | jq -r '.Distribution.Status')
+            echo "🔄 Estado actual: $STATUS"
+            if [ "$STATUS" == "Deployed" ]; then
+              echo -e "\n✅ CloudFront Distribution $(CLOUDFRONT_ID) propagada correctamente."
+              break
+            fi
+            sleep 10
+          done
+        displayName: "⏳ Waiting for CloudFront propagation"
+        env:
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
+          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
+
+      - script: |
+          echo -e "\n⏳ Esperando que CloudFront Distribution $(CLOUDFRONT_ID) invalide..."
+
+          RESULT=$(aws cloudfront create-invalidation --distribution-id $(CLOUDFRONT_ID) --paths '/*')
+          INVALIDATION=$(echo "$RESULT" | jq -r '.Invalidation.Id')
+
+          echo -e "\n🆔 ID de invalidación: $INVALIDATION"
+          echo "$RESULT"
+
+          while true; do
+            STATUS=$(aws cloudfront get-invalidation --distribution-id $(CLOUDFRONT_ID) --id "$INVALIDATION" --region $AWS_DEFAULT_REGION | jq -r '.Invalidation.Status')
+            echo "🔄 Estado actual de la invalidación: $STATUS"
+            if [ "$STATUS" == "Completed" ]; then
+              echo -e "\n✅ Invalidacion $INVALIDATION completada con éxito."
+              break
+            fi
+            sleep 10
+          done
+        displayName: "⏳ Waiting for invalidation Cache"
+        env:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
