Updates

diff --git a/pipeline/cd/deploy/deploy-backend.yml b/pipeline/cd/deploy/deploy-backend.yml
--- a/pipeline/cd/deploy/deploy-backend.yml
+++ b/pipeline/cd/deploy/deploy-backend.yml
@@ -1,6 +1,6 @@
 jobs:
   - job: deploy_micro_service
-    displayName: "🚀 Deploy Docker Image"
+    displayName: "🚀 Deploy Microservice"
     pool:
       name: "Azure Pipelines"
       VmImage: ubuntu-22.04
@@ -261,14 +261,39 @@ jobs:
           AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
 
-      # - script: |
-      #     echo -e "\nℹ️ Obteniendo family de task definition..."
-      #     ARN='$(taskDefinitionArn)'
-      #     echo $ARN
-      #     FAMILY=$(echo $ARN | cut -d'/' -f2 | cut -d':' -f1)
-      #     echo "##vso[task.setvariable variable=taskFamily]$FAMILY"
-      #   displayName: "📌 Extract Family from ARN"
-      #   condition: succeeded()
+      - script: |
+          echo -e "\nℹ️ Obteniendo family de task definition..."
+          ARN='$(taskDefinitionArn)'
+          echo $ARN
+          FAMILY=$(echo $ARN | cut -d'/' -f2 | cut -d':' -f1)
+          echo "##vso[task.setvariable variable=taskFamily]$FAMILY"
+        displayName: "📌 Extract Family from ARN"
+        condition: and(succeeded(),
+          ne(variables['cleanMsName'], 'transaction'))
+      
+      - script: |
+          echo -e "\nℹ️ Extrayendo FAMILY para todos los taskDefinitionArn_X..."
+
+          for i in 0 1 2 3; do
+            ARN_VAR="taskDefinitionArn_${i}"
+            ARN_VALUE="${!ARN_VAR}"
+
+            echo -e "\n📌 Procesando índice $i"
+            echo "ARN recibido: $ARN_VALUE"
+
+            if [[ -z "$ARN_VALUE" ]]; then
+              echo "❌ Error: ARN vacío para índice $i"
+              exit 98
+            fi
+
+            FAMILY=$(echo "$ARN_VALUE" | cut -d'/' -f2 | cut -d':' -f1)
+            echo "FAMILY: $FAMILY"
+
+            echo "##vso[task.setvariable variable=taskFamily_${i}]$FAMILY"
+          done
+        displayName: "📌 Extract Family from ARN"
+        condition: and(succeeded(),
+          eq(variables['cleanMsName'], 'transaction'))
 
       # - script: |
       #     export AWS_ACCESS_KEY_ID
