chore: refactor files

diff --git a/pipeline/cd/deploy/reload-version-ecs.yml b/pipeline/cd/deploy/reload-version-ecs.yml
--- a/pipeline/cd/deploy/reload-version-ecs.yml
+++ b/pipeline/cd/deploy/reload-version-ecs.yml
@@ -23,25 +23,31 @@ jobs:
           set -e
           cp $(Pipeline.Workspace)/versions-downloaded/versions/microservices/version.json $(System.DefaultWorkingDirectory)/services.json
           export CLUSTER="invictus"
-          echo "✅ Servicios a reiniciar:"
 
-          SERVICES_JSON=$(cat services.json)
+          echo "✅ Servicios a reiniciar:"
           jq . services.json
           echo ""
 
+          SERVICES_JSON=$(cat services.json)
           for SERVICE in $(echo "$SERVICES_JSON" | jq -r 'keys[]'); do
             echo "🔄 Reiniciando $SERVICE..."
 
-            aws ecs update-service \
+            OUTPUT=$(aws ecs update-service \
               --cluster "$CLUSTER" \
               --service "$SERVICE" \
-              --force-new-deployment
+              --force-new-deployment 2>&1)
 
-            echo "✅ $SERVICE reiniciado"
+            STATUS=$?
+
+            if [ $STATUS -ne 0 ]; then
+              echo "❌ Error reiniciando $SERVICE"
+              echo "$OUTPUT"
+              echo -e "\n##vso[task.logissue type=error]⚠️ Error en servicio [$SERVICE]"
+              exit 99
+            fi
+
+            echo "✅ $SERVICE reiniciado correctamente"
             echo "---------------------------------------------"
           done
         displayName: "🚀 Reiniciando Microservices"
-        env:
-          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
-          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
-          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
+        condition: succeeded()
