feat: refactor tasks
Co-authored-by: Copilot <copilot@github.com>

diff --git a/pipeline/ci/tests/sonarqube-frontend.yml b/pipeline/ci/tests/sonarqube-frontend.yml
--- a/pipeline/ci/tests/sonarqube-frontend.yml
+++ b/pipeline/ci/tests/sonarqube-frontend.yml
@@ -32,41 +32,49 @@ jobs:
         displayName: "📥 Download Version"
         condition: succeeded()
 
-      - script: |
-          VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/$(msName)/version.json"
-          echo -e "\n📁 Archivo version.json:"
-          ls -la "$VERSION_FILE"
-          jq . "$VERSION_FILE"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/$(msName)/version.json"
+            echo -e "\n📁 Archivo version.json:"
+            ls -la "$VERSION_FILE"
+            jq . "$VERSION_FILE"
 
-          if [[ -f "$VERSION_FILE" ]]; then
-            VERSION=$(jq -r '.version' $VERSION_FILE)
-            echo -e "\n🚀 Versión detectada para $(msName): $VERSION"
-            echo "##vso[task.setvariable variable=msVersion]$VERSION"
-          else
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró archivo de versión para: $(msName)" 
-            exit 99
-          fi
+            if [[ -f "$VERSION_FILE" ]]; then
+              VERSION=$(jq -r '.version' $VERSION_FILE)
+              echo -e "\n🚀 Versión detectada para $(msName): $VERSION"
+              echo "##vso[task.setvariable variable=msVersion]$VERSION"
+            else
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró archivo de versión para: $(msName)" 
+              exit 99
+            fi
         displayName: "📚 Read Version"
         condition: succeeded()
 
-      - script: |
-          if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
-            fileselect=app-legacy
-            echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
-            echo "##vso[task.setvariable variable=file]$fileselect"
-          else
-            fileselect=apps
-            echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
-            echo "##vso[task.setvariable variable=file]$fileselect"
-          fi
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
+              fileselect=app-legacy
+              echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
+              echo "##vso[task.setvariable variable=file]$fileselect"
+            else
+              fileselect=apps
+              echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
+              echo "##vso[task.setvariable variable=file]$fileselect"
+            fi
         displayName: "📂 Select Directory"
         condition: succeeded()
 
       - task: Bash@3
-        name: AuthCodeArtifact
         inputs:
-          targetType: "inline"
+          targetType: inline
           script: |
+            set -e
             echo "🔐 Obteniendo token de AWS CodeArtifact..."
             token=$(aws codeartifact get-authorization-token \
               --domain matrixtech-npm-repository \
@@ -92,6 +100,8 @@ jobs:
             //$REPO_DOMAIN/$REPO_PATH/:_authToken=$token
             registry=$REPO_URL
             EOF
+
+            echo -e "\n✅ .npmrc generado"
             ls -l $npmrcPath
         displayName: "🔐 Setup CodeArtifact & npm config"
         condition: succeeded()
@@ -101,73 +111,85 @@ jobs:
           AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
 
       - task: UseNode@1
-        displayName: "🔧 Install Nodejs $(nodeVersion)"
         inputs:
           version: "$(nodeVersion)"
+        displayName: "🔧 Install Nodejs $(nodeVersion)"
         condition: succeeded()
 
-      - script: |
-          echo "Comentando app-legacy/*"
-          cd $(Build.Repository.Name)
-          sed -i '/app-legacy\//s/  -/  # -/' pnpm-workspace.yaml
-          cat pnpm-workspace.yaml
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo "Comentando app-legacy/*"
+            cd $(Build.Repository.Name)
+            sed -i '/app-legacy\//s/  -/  # -/' pnpm-workspace.yaml
+            cat pnpm-workspace.yaml
         displayName: "💬 Comment app-legacy/*"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'))
 
-      - script: |
-          rm "$(Build.Repository.Name)/$(file)/$(msName)/vitest.config.mts"
-          echo -e "\n✅ Elimnación archivo vitest.config.mts ..."
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            rm "$(Build.Repository.Name)/$(file)/$(msName)/vitest.config.mts"
+            echo -e "\n✅ Elimnación archivo vitest.config.mts ..."
 
-          cp pipelines-templates/pipeline/config/vitest.config.mts $(Build.Repository.Name)/$(file)/$(msName)
-          echo "⚠️ Copiando archivo vitest.config.mts templates..."
+            cp pipelines-templates/pipeline/config/vitest.config.mts $(Build.Repository.Name)/$(file)/$(msName)
+            echo "⚠️ Copiando archivo vitest.config.mts templates..."
 
-          echo "✅ vitest.config.mts copiado exitosamente."
-          echo -e "\n📁 Files:"
-          ls -la $(Build.Repository.Name)/$(file)/$(msName)
-          cat $(Build.Repository.Name)/$(file)/$(msName)/vitest.config.mts
+            echo "✅ vitest.config.mts copiado exitosamente."
+            echo -e "\n📁 Files:"
+            ls -la $(Build.Repository.Name)/$(file)/$(msName)
+            cat $(Build.Repository.Name)/$(file)/$(msName)/vitest.config.mts
 
-          FILE="$(Build.Repository.Name)/$(file)/$(msName)/vitest.config.ts"
-          if [[ -f "$FILE" ]]; then
-            rm "$FILE"
-            echo "❌ Eliminando el archivo vitest.config.ts"
-          fi
+            FILE="$(Build.Repository.Name)/$(file)/$(msName)/vitest.config.ts"
+            if [[ -f "$FILE" ]]; then
+              rm "$FILE"
+              echo "❌ Eliminando el archivo vitest.config.ts"
+            fi
         displayName: "♻️ Replace vitest.config"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'))
 
-      - script: |
-          echo -e "\n📁 Generando archivo .pnpmrc en: $(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc"
-          cat <<EOF > "$(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc"
-          node-linker=hoisted
-          shamefully-hoist=true
-          ignore-scripts=false
-          allow-build-script=true
-          strict-peer-dependencies=false
-          EOF
-          ls -l $(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc
-          cat $(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            echo -e "\n📁 Generando archivo .pnpmrc en: $(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc"
+            cat <<EOF > "$(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc"
+            node-linker=hoisted
+            shamefully-hoist=true
+            ignore-scripts=false
+            allow-build-script=true
+            strict-peer-dependencies=false
+            EOF
+            ls -l $(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc
+            cat $(Build.Repository.Name)/$(file)/$(msName)/.pnpmrc
 
-          # cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
-          cd $(Build.Repository.Name)
-          echo -e "\n⚙️ Instalando dependencias node..."
-          npm install -g pnpm
-          pnpm install
+            # cd $(System.DefaultWorkingDirectory)/$(file)/$(msName)
+            cd $(Build.Repository.Name)
+            echo -e "\n⚙️ Instalando dependencias node..."
+            npm install -g pnpm
+            pnpm install
 
-          cd $(Build.Repository.Name)/$(file)/$(msName)
-          ls -la 
-          # pnpm ignored-builds
+            cd $(Build.Repository.Name)/$(file)/$(msName)
+            ls -la 
+            # pnpm ignored-builds
 
-          OUTPUT=$(pnpm ls --depth=0 || true)
-          if [[ -z "$OUTPUT" ]]; then
-            echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
-            exit 99
-          else
-            echo -e "\n✅ Dependencias Instaladas:"
-            echo "$OUTPUT"
-          fi
+            OUTPUT=$(pnpm ls --depth=0 || true)
+            if [[ -z "$OUTPUT" ]]; then
+              echo -e "\n##vso[task.logissue type=error]⚠️ No se instalaron dependencias, esperar que se actualicen las dependencias a nivel global"
+              exit 99
+            else
+              echo -e "\n✅ Dependencias Instaladas:"
+              echo "$OUTPUT"
+            fi
         displayName: "⚙️ Install Dependencies"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
@@ -175,17 +197,16 @@ jobs:
           ne(variables['Build.SourceBranchName'], 'develop'))
 
       - task: JavaToolInstaller@0
-        displayName: "🔧 Install JDK 17"
         inputs:
           versionSpec: "17"
           jdkArchitectureOption: "x64"
           jdkSourceOption: "PreInstalled"
+        displayName: "🔧 Install JDK 17"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'))
 
       - task: SonarQubePrepare@7
-        displayName: "⚙️ Prepare SonarQube Analysis"
         inputs:
           SonarQube: "SonarQubeConection"
           scannerMode: "CLI"
@@ -198,28 +219,37 @@ jobs:
             sonar.projectTags=invictus
             sonar.javascript.lcov.reportPaths=$(Build.Repository.Name)/$(file)/$(msName)/coverage/lcov.info
             sonar.exclusions=**/test/**,**/coverage/**,**/.nyc_output/**,**/reports/**,sured-plugin/**,**/reports_bck/**,**/node_modules/**,**/dist/**,*.cjs,*mts,**/main.ts,**/config/**,**/config.*,**/**.config.*
+        displayName: "⚙️ Prepare SonarQube Analysis"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'),
           ne(variables['Build.SourceBranchName'], 'develop'))
 
-      - script: |
-          response=$(echo $SONARQUBE_SCANNER_PARAMS | sed -E 's#"sonar\.branch\.name":"[^"]+",##g')
-          json=$(echo "$response" | sed 's/"sonar.token":\*\*\*/"sonar.token":"***"/')
-          echo "$json" | jq
-          echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$response"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            response=$(echo $SONARQUBE_SCANNER_PARAMS | sed -E 's#"sonar\.branch\.name":"[^"]+",##g')
+            json=$(echo "$response" | sed 's/"sonar.token":\*\*\*/"sonar.token":"***"/')
+            echo "$json" | jq
+            echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$response"
         displayName: "⚙️ Set Variable — SONARQUBE_SCANNER_PARAMS"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'),
           ne(variables['Build.SourceBranchName'], 'develop'))
 
-      - script: |
-          cd $(Build.Repository.Name)
-          pnpm coverage --filter=...$(msName)
-          ls -l "$(file)/$(msName)/coverage"
-        displayName: "🔎 Coverage Analysis: $(msName)"
+      - task: Bash@3
+        inputs:
+          targetType: inline
+          script: |
+            set -e
+            cd $(Build.Repository.Name)
+            pnpm coverage --filter=...$(msName)
+            ls -l "$(file)/$(msName)/coverage"
         continueOnError: true
+        displayName: "🔎 Coverage Analysis: $(msName)"
         condition: and(succeeded(),
           ne(variables['msName'], 'app-administration-vue2'),
           ne(variables['msName'], 'app-sellers-vue2'),
