Update file

diff --git a/pipeline/ci/pre-build/changes-files-frontend.yml b/pipeline/ci/pre-build/changes-files-frontend.yml
--- a/pipeline/ci/pre-build/changes-files-frontend.yml
+++ b/pipeline/ci/pre-build/changes-files-frontend.yml
@@ -48,44 +48,46 @@ jobs:
 
           case "$(Build.Reason)" in
             "PullRequest")
-              cd $(Build.SourcesDirectory)
-              clean_branch=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
-              git checkout $clean_branch
-              git reset --hard HEAD
-
               SOURCE_BRANCH=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
               TARGET_BRANCH=$(echo "$(System.PullRequest.TargetBranch)" | sed 's#refs/heads/##')
               CURRENT_BRANCH=$SOURCE_BRANCH
-          
-              echo -e "\n🔍 Comparando cambios entre: $TARGET_BRANCH ... $CURRENT_BRANCH"
-              changed_files=$(git diff --name-only "origin/$TARGET_BRANCH"..."origin/$CURRENT_BRANCH")
-              packages_changed=$(echo "$changed_files" | grep "^packages/" || true)
 
-              if [[ -n "$packages_changed" ]]; then
-                apps=$(find apps app-legacy -mindepth 1 -maxdepth 1 -type d | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
-              else
-                apps=$(echo "$changed_files" | grep -E "^apps/|^app-legacy/" | cut -d '/' -f1,2 | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
+              if [[ "$SOURCE_BRANCH" == feature/* || "$SOURCE_BRANCH" == hotfix/* ]]; then
+                cd $(Build.SourcesDirectory)
+                clean_branch=$(echo "$(System.PullRequest.SourceBranch)" | sed 's#refs/heads/##')
+                git checkout $clean_branch
+                git reset --hard HEAD
+
+                echo -e "\n🔍 Comparando cambios entre: $TARGET_BRANCH ... $CURRENT_BRANCH"
+                changed_files=$(git diff --name-only "origin/$TARGET_BRANCH"..."origin/$CURRENT_BRANCH")
+                packages_changed=$(echo "$changed_files" | grep "^packages/" || true)
+
+                if [[ -n "$packages_changed" ]]; then
+                  apps=$(find apps app-legacy -mindepth 1 -maxdepth 1 -type d | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
+                else
+                  apps=$(echo "$changed_files" | grep -E "^apps/|^app-legacy/" | cut -d '/' -f1,2 | sed -E 's|^app[-]?legacy/||; s|^apps/||' | sort -u)
+                fi
+
+                if [[ -z "$apps" ]]; then
+                  echo -e "\n##vso[task.logissue type=error]⚠️ No se detectaron cambios en apps. Cancelando ejecución del pipeline."
+                  exit 99
+                fi
+                
+                echo "🔍 Apps modificadas detectadas:"
+                echo "${apps[@]}"
+                apps_json=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s .)
+
+                echo -e "\n🔗 Creando ejecucion pipeline"
+                pipeline_output=$(az pipelines run \
+                  --name "apps-microfrontend-invictus" \
+                  --branch "$CURRENT_BRANCH" \
+                  --parameters pr_id="$(System.PullRequest.PullRequestId)" apps="$apps_json" \
+                  --output json)
+                echo "$pipeline_output" | jq
+
+                run_id=$(echo "$pipeline_output" | jq -r '.id')              
+                echo -e "\n##[command]🌐 Build Results URL: https://dev.azure.com/ux-technology/Invictus/_build/results?buildId=$run_id"
               fi
-
-              if [[ -z "$apps" ]]; then
-                echo -e "\n##vso[task.logissue type=error]⚠️ No se detectaron cambios en apps. Cancelando ejecución del pipeline."
-                exit 99
-              fi
-              
-              echo "🔍 Apps modificadas detectadas:"
-              echo "${apps[@]}"
-              apps_json=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s .)
-
-              echo -e "\n🔗 Creando ejecucion pipeline"
-              pipeline_output=$(az pipelines run \
-                --name "apps-microfrontend-invictus" \
-                --branch "$CURRENT_BRANCH" \
-                --parameters pr_id="$(System.PullRequest.PullRequestId)" apps="$apps_json" \
-                --output json)
-              echo "$pipeline_output" | jq
-
-              run_id=$(echo "$pipeline_output" | jq -r '.id')              
-              echo -e "\n##[command]🌐 Build Results URL: https://dev.azure.com/ux-technology/Invictus/_build/results?buildId=$run_id"
               ;;
             "IndividualCI")
                 cd $(Build.SourcesDirectory)
